#********************************************************************
# Salt Event Processor Properties
#********************************************************************
# Java Application

EVENT_PROCESSOR_LIBRARY_PATH="/usr/lib:/usr/lib64"
EVENT_PROCESSOR_RHN_CLASSPATH="/usr/share/rhn/classes"
EVENT_PROCESSOR_RHN_JARS="/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar"
EVENT_PROCESSOR_JARS="/usr/share/spacewalk/taskomatic/*"
EVENT_PROCESSOR_JAVA_OPTS=""
EVENT_PROCESSOR_INIT_MEMORY=128
EVENT_PROCESSOR_MAX_MEMORY=512
JAVA_OPTS="-Xdebug -Xrunjdwp:transport=dt_socket,address=*:8007,server=y,suspend=n "