#!/bin/sh
# SaltEventProcessorDaemon start script
echo "Loading Salt Event Processor configuration..."
. /etc/rhn/saltEventProcessor.conf
echo "Configuration loaded successfully"

SALTEN_PARAMS="-Dibm.dst.compatibility=true -Dfile.encoding=UTF-8 -Xms${SALTEN_INIT_MEMORY}m -Xmx${SALTEN_MAX_MEMORY}m ${SALTEN_CRASH_PARAMS} ${SALTEN_JAVA_OPTS}"
SALTEN_CLASSPATH="${SALTEN_RHN_CLASSPATH}:${SALTEN_RHN_JARS}:${SALTEN_JARS}"

# Add logging configuration
LOG4J_CONFIG="-Dlog4j2.configurationFile=file:///usr/share/rhn/classes/log4j2_saltEventProcessor.xml"

echo "Starting Salt Event Processor..."
# options sourced from /usr/share/rhn/config-defaults/rhn_saltEventProcessor_daemon.conf (do not touch). Add additional options to /etc/rhn/saltEventProcessor.conf
/usr/bin/java -Djava.library.path=${SALTEN_LIBRARY_PATH} -classpath ${SALTEN_CLASSPATH} ${SALTEN_PARAMS} ${LOG4J_CONFIG} ${JAVA_OPTS} ${JAVA_AGENT} com.suse.saltevent.SaltEventProcessor
