/*
 * Copyright (c) 2026 SUSE LLC
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 */
package com.redhat.rhn.frontend.xmlrpc.audit;

import com.redhat.rhn.domain.user.User;
import com.redhat.rhn.manager.audit.CVEAuditImage;
import com.redhat.rhn.manager.audit.CVEAuditServer;

import com.suse.manager.api.ApiResponseWrapper;
import com.suse.manager.api.docs.ApiEndpointDoc;
import com.suse.manager.api.docs.LegacyDocResponse;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.List;

import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.extensions.Extension;
import io.swagger.v3.oas.annotations.extensions.ExtensionProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.tags.Tag;
import spark.route.HttpMethod;

/**
 * API contract for {@link CVEAuditHandler}.
 */
@Tag(name = "audit", description = "Methods to audit systems.")
public interface CVEAuditHandlerApi {

    /**
     * Lists visible systems with their patch status for a given CVE identifier.
     *
     * @param loggedInUser the current user
     * @param cveIdentifier the CVE identifier
     * @param patchStatusLabels the patch status labels to filter by
     * @return the systems with their patch status
     */
    @ApiEndpointDoc(
        summary = "List visible systems with their patch status regarding a given CVE identifier. Filter the " +
            "results by passing in a list of patch status labels. Please note that the query code relies on " +
            "data that is pre-generated by the 'cve-server-channels' taskomatic job.",
        method = HttpMethod.get,
        responseClass = CVEAuditSystemListResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "CVE audit system")
    )
    List<CVEAuditServer> listSystemsByPatchStatus(
        @Parameter(hidden = true) User loggedInUser,
        @Parameter(name = "cveIdentifier", in = ParameterIn.QUERY, required = true) String cveIdentifier,
        @Parameter(name = "patchStatusLabels", in = ParameterIn.QUERY, required = false,
            schema = @Schema(allowableValues = {"AFFECTED_PATCH_INAPPLICABLE", "AFFECTED_PATCH_APPLICABLE",
                "NOT_AFFECTED", "PATCHED"},
                extensions = @Extension(name = "x-uyuni-doc-option-descriptions", properties = {
                    @ExtensionProperty(name = "AFFECTED_PATCH_INAPPLICABLE",
                        value = "Affected, patch available in unassigned channel"),
                    @ExtensionProperty(name = "AFFECTED_PATCH_APPLICABLE",
                        value = "Affected, patch available in assigned channel"),
                    @ExtensionProperty(name = "NOT_AFFECTED", value = "Not affected"),
                    @ExtensionProperty(name = "PATCHED", value = "Patched")
                }))) List<String> patchStatusLabels);

    /**
     * Lists visible images with their patch status for a given CVE identifier.
     *
     * @param loggedInUser the current user
     * @param cveIdentifier the CVE identifier
     * @param patchStatusLabels the patch status labels to filter by
     * @return the images with their patch status
     */
    @ApiEndpointDoc(
        summary = "List visible images with their patch status regarding a given CVE identifier. Filter the " +
            "results by passing in a list of patch status labels. Please note that the query code relies on " +
            "data that is pre-generated by the 'cve-server-channels' taskomatic job.",
        method = HttpMethod.get,
        responseClass = CVEAuditImageListResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "CVE audit image")
    )
    List<CVEAuditImage> listImagesByPatchStatus(
        @Parameter(hidden = true) User loggedInUser,
        @Parameter(name = "cveIdentifier", in = ParameterIn.QUERY, required = true) String cveIdentifier,
        @Parameter(name = "patchStatusLabels", in = ParameterIn.QUERY, required = false,
            schema = @Schema(allowableValues = {"AFFECTED_PATCH_INAPPLICABLE", "AFFECTED_PATCH_APPLICABLE",
                "NOT_AFFECTED", "PATCHED"},
                extensions = @Extension(name = "x-uyuni-doc-option-descriptions", properties = {
                    @ExtensionProperty(name = "AFFECTED_PATCH_INAPPLICABLE",
                        value = "Affected, patch available in unassigned channel"),
                    @ExtensionProperty(name = "AFFECTED_PATCH_APPLICABLE",
                        value = "Affected, patch available in assigned channel"),
                    @ExtensionProperty(name = "NOT_AFFECTED", value = "Not affected"),
                    @ExtensionProperty(name = "PATCHED", value = "Patched")
                }))) List<String> patchStatusLabels);

    @Schema(name = "ApiResponseCVEAuditSystemList")
    interface CVEAuditSystemListResponse extends ApiResponseWrapper<List<CVEAuditSystemDoc>> { }

    @Schema(name = "ApiResponseCVEAuditImageList")
    interface CVEAuditImageListResponse extends ApiResponseWrapper<List<CVEAuditImageDoc>> { }

    @Schema(name = "CVEAuditSystem", description = "CVE audit system")
    @JsonPropertyOrder({"systemId", "patchStatus", "channelLabels", "errataAdvisories"})
    interface CVEAuditSystemDoc {

        /**
         * @return the system id
         */
        @Schema(name = "system_id", requiredMode = Schema.RequiredMode.REQUIRED)
        Long getSystemId();

        /**
         * @return the patch status
         */
        @Schema(name = "patch_status", requiredMode = Schema.RequiredMode.REQUIRED,
                allowableValues = {"AFFECTED_PATCH_UNAVAILABLE", "AFFECTED_PATCH_UNAVAILABLE_IN_UYUNI",
                    "AFFECTED_PATCH_INAPPLICABLE", "AFFECTED_PATCH_INAPPLICABLE_SUCCESSOR_PRODUCT",
                    "AFFECTED_PARTIAL_PATCH_APPLICABLE", "AFFECTED_FULL_PATCH_APPLICABLE", "NOT_AFFECTED",
                    "PATCHED", "UNKNOWN"},
                extensions = @Extension(name = "x-uyuni-doc-option-descriptions", properties = {
                    @ExtensionProperty(name = "AFFECTED_PATCH_UNAVAILABLE",
                        value = "affected, patch is unavailable anywhere"),
                    @ExtensionProperty(name = "AFFECTED_PATCH_UNAVAILABLE_IN_UYUNI",
                        value = "affected, patch is unavailable in any of the synced channels"),
                    @ExtensionProperty(name = "AFFECTED_PATCH_INAPPLICABLE",
                        value = "affected, patch available in unassigned channel"),
                    @ExtensionProperty(name = "AFFECTED_PATCH_INAPPLICABLE_SUCCESSOR_PRODUCT",
                        value = "affected, patch available in a Product Migration target"),
                    @ExtensionProperty(name = "AFFECTED_PARTIAL_PATCH_APPLICABLE",
                        value = "affected, partial patch available in assigned channel"),
                    @ExtensionProperty(name = "AFFECTED_FULL_PATCH_APPLICABLE",
                        value = "affected, full patch available in assigned channel"),
                    @ExtensionProperty(name = "NOT_AFFECTED", value = "not affected"),
                    @ExtensionProperty(name = "PATCHED", value = "patched"),
                    @ExtensionProperty(name = "UNKNOWN", value = "unknown, CVE metadata not available")
                }))
        String getPatchStatus();

        /**
         * @return the labels of channels that contain an unapplied patch
         */
        @Schema(name = "channel_labels", description = "labels of channels that contain an unapplied patch",
                requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getChannelLabels();

        /**
         * @return the advisories of erratas that patch the vulnerability
         */
        @Schema(name = "errata_advisories",
                description = "advisories of erratas that patch the specified vulnerability",
                requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getErrataAdvisories();
    }

    @Schema(name = "CVEAuditImage", description = "CVE audit image")
    @JsonPropertyOrder({"imageId", "patchStatus", "channelLabels", "errataAdvisories"})
    interface CVEAuditImageDoc {

        /**
         * @return the image id
         */
        @Schema(name = "image_id", requiredMode = Schema.RequiredMode.REQUIRED)
        Long getImageId();

        /**
         * @return the patch status
         */
        @Schema(name = "patch_status", requiredMode = Schema.RequiredMode.REQUIRED,
                allowableValues = {"AFFECTED_PATCH_UNAVAILABLE", "AFFECTED_PATCH_UNAVAILABLE_IN_UYUNI",
                    "AFFECTED_PATCH_INAPPLICABLE", "AFFECTED_PATCH_INAPPLICABLE_SUCCESSOR_PRODUCT",
                    "AFFECTED_PARTIAL_PATCH_APPLICABLE", "AFFECTED_FULL_PATCH_APPLICABLE", "NOT_AFFECTED",
                    "PATCHED", "UNKNOWN"},
                extensions = @Extension(name = "x-uyuni-doc-option-descriptions", properties = {
                    @ExtensionProperty(name = "AFFECTED_PATCH_UNAVAILABLE",
                        value = "affected, patch is unavailable anywhere"),
                    @ExtensionProperty(name = "AFFECTED_PATCH_UNAVAILABLE_IN_UYUNI",
                        value = "affected, patch is unavailable in any of the synced channels"),
                    @ExtensionProperty(name = "AFFECTED_PATCH_INAPPLICABLE",
                        value = "affected, patch available in unassigned channel"),
                    @ExtensionProperty(name = "AFFECTED_PATCH_INAPPLICABLE_SUCCESSOR_PRODUCT",
                        value = "affected, patch available in a Product Migration target"),
                    @ExtensionProperty(name = "AFFECTED_PARTIAL_PATCH_APPLICABLE",
                        value = "affected, partial patch available in assigned channel"),
                    @ExtensionProperty(name = "AFFECTED_FULL_PATCH_APPLICABLE",
                        value = "affected, full patch available in assigned channel"),
                    @ExtensionProperty(name = "NOT_AFFECTED", value = "not affected"),
                    @ExtensionProperty(name = "PATCHED", value = "patched"),
                    @ExtensionProperty(name = "UNKNOWN", value = "unknown, CVE metadata not available")
                }))
        String getPatchStatus();

        /**
         * @return the labels of channels that contain an unapplied patch
         */
        @Schema(name = "channel_labels", description = "labels of channels that contain an unapplied patch",
                requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getChannelLabels();

        /**
         * @return the advisories of erratas that patch the vulnerability
         */
        @Schema(name = "errata_advisories",
                description = "advisories of erratas that patch the specified vulnerability",
                requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getErrataAdvisories();
    }
}
