.\" Copyright 2017 SUSE LLC
.\"
.\" This man page is free documentation; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; version 2 of the License.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this man page; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.TH SSL-CERT-CHECK 8 "2017 December 10" "Linux" "SUSE LLC"

.SH NAME
ssl-cert-check \- check expiration of SSL Certificates.

.SH SYNOPSIS

ssl-cert-check [\fIoptions\fP]

.SH DESCRIPTION
.PP
\fVssl-cert-check\fR check expiration of SSL Certificates and write messages if the certificate expired in less than given days or when the certificate is already expired. If the "\fB--mail\fP" option is provided \fVssl-cert-check\fR will send an email to the configured default destination of your "\fBSpacewalk Server\fP", "\fBSUSE Manager Server\fP".

.SH OPTIONS

.IP "\fB-p, --path\fP"
Path to the SSL Certificate which should be checked.
.br
.IP "\fB-d, --days\fP"
Days before expiration to warn.
.br
.IP "\fB-m, --mail\fP"
Send an email for errors and warnings.
.br
.IP "\fB-h, --help\fP"
Show a help message and exit.

.SH "EXAMPLES"

Check the certificate and warn via email 40 days before it expires:

.RS
.nf
ssl-cert-check --path /srv/www/htdocs/pub/RHN-ORG-TRUSTED-SSL-CERT --days 40 --mail
.fi
.RE

.SH AUTHORS
.PP
Michael Calmer <mc@suse.com>

.SH "BUGS"
.PP
Report bugs to <http://bugzilla.suse.com>.

.SH COPYRIGHT

.PP
Copyright \(co 2017 SUSE LLC.

.PP
This is free software; see the source for copying conditions.  There is 
NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
