#!/bin/bash

# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

#
# start script
#

pushd $(dirname $0)

SYSCONFIG=/etc/sysconfig/billing-data-service
test -f $SYSCONFIG && . $SYSCONFIG

OPTIONS=${ARGS}
export FLASK_APP=billingdataservice.py
export WERKZEUG_RUN_MAIN="true"

/usr/bin/flask run --host=${LISTEN} --port=${PORT} ${OPTIONS}

