# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the xmlrpc module
#

TOP	= ../../..
SUBDIR	= server/handlers/xmlrpc

FILES	= __init__  proxy get_handler

include $(TOP)/Makefile.defs

