= Content Lifecycle Managment

Content Lifecycle Management allows you to customize and test packages before updating production systems.
This is especially useful if you need to apply updates during a limited maintenance window.

You can use Content Lifecycle Management to select software channels as sources, adjust them as required for your environment, and thoroughly test them before installing onto your production systems.

While you cannot directly modify vendor channels, you can clone them and then modify the clones by adding or removing packages and custom patches. 
You can then assign these cloned channels to test systems to ensure they work as expected and, once all tests pass, apply them to production servers.

This is achieved through a series of environments that your software channels can move through on their lifecycle. 
Most environment lifecycles include at least test and production environments, but you can have as many environments as you require.

[WARNING]
====
This feature is not yet complete!
The documentation for this feature is being offered as a preview of changes to come.
====
