[[iss]]
= Inter-Server Synchronization

If you have more than one {productname} installation, you will probably want to ensure that they stay aligned on content and permissions.
Inter-Server Synchronization (ISS) allows you to connect two or more {productname} servers and keep them up-to-date.

To set up ISS, you need to define one {productname} server as a master, with the other as a slave.
If conflicting configurations exist, the system will prioritize the master configuration.

.Procedure: Setting up an ISS Master

. In the {productname} {webui}, navigate to menu:Admin[ISS Configuration > Slave Setup], and click btn:[Add new master].
. In the [guimenu]``Details for new Master`` dialog, provide these details for the server to use as the ISS master:

* In the [guimenu]``Master Fully-Qualified Domain Name`` field, enter the FQDN of the ISS master (for example: [systemitem]``server1.example.com``).
* In the [guimenu]``Filename of this Master's CA Certificate`` field, enter the absolute  path to the CA certificate on the ISS master (for example: [systemitem]``/etc/pki/trust/anchors/RHN-ORG-TRUSTED-SSL-CERT``).
Click btn:[Add new master] to add the ISS master.

.Procedure: Setting up an ISS Slave

. In the {productname} {webui}, navigate to menu:Admin[ISS Configuration > Master Setup], and click btn:[Add new slave].
. In the [guimenu]``Edit Slave Details`` dialog, for the server to use as the ISS slave provide these details:

* In the [guimenu]``Slave Fully-Qualified Domain Name`` field, enter the FQDN of the ISS slave (for example: [systemitem]``server2.example.com``).
* Check the [guimenu]``Allow Slave to Sync?`` checkbox to enable the slave to synchronize with the master.
* Check the [guimenu]``Sync All Orgs to Slave?`` checkbox to synchronize all organizations to this slave.
. Click btn:[Create] to add the ISS slave.
. In the [guimenu]``Allow Export of the Selected Organizations`` section, check the organizations you want to allow this slave to export to the master, and click btn:[Allow Orgs].

When you have the master and slaves set up, you can perform a synchronization from the command line on the slave, with this command:

----
mgr-inter-sync
----
