[[troubleshooting-disk-space]]
= Troubleshooting Disk Space

////
PUT THIS COMMENT AT THE TOP OF TROUBLESHOOTING SECTIONS

Troubleshooting format:

One sentence each:
Cause: What created the problem?
Consequence: What does the user see when this happens?
Fix: What can the user do to fix this problem?
Result: What happens after the user has completed the fix?

If more detailed instructions are required, put them in a "Resolving" procedure:
.Procedure: Resolving Widget Wobbles
. First step
. Another step
. Last step
////

Running out of disk space can have a severe impact on the {productname} database and file structure which, in most cases, is not recoverable.

{productname} monitors free space in specific directories, and has configurable alerts.
For more on space management, see xref:administration:space-management.adoc[].

You can recover disk space by removing unused custom channels and redundant database entries before you run out of space entirely.

For instructions on how to delete custom channels, see xref:administration:channel-management.adoc[].

.Procedure: Resolving redundant database entries
. Use the [command]``spacewalk-data-fsck`` command to list any redundant database entries.
. Use the [command]``spacewalk-data-fsck --remove`` command to delete them.
