set address [lindex $argv 0]

spawn /usr/bin/ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $address
match_max 100000
expect "*?assword:*"
send -- "linux\r"
expect "#"
send -- "curl -O -L http://proxy.example.org/pub/bootstrap/bootstrap.sh\r"
expect "#"
send -- "chmod 750 /root/bootstrap.sh\r"
expect "#"
send -- "bash -x /root/bootstrap.sh\r"
set timeout 180
expect "?bootstrap complete?"
puts "\r"
