# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the backend directory
#

TOP = ..

SUBDIRS = pxt rhn

include $(TOP)/Makefile.defs
# whitespace change to test checkin
