[[bind-formula]]
= Bind Formula

The Bind formula is used to configure the Domain Name System (DNS) on the branch server.
POS terminals will use the DNS on the branch server for name resolution of saltboot specific hostnames.

When you are configuring the Bind formula for a branch server with a dedicated internal network, check that you are using the same fully qualified domain name (FQDN) on both the external and internal branch networks.
If the FQDN does not match on both networks, the branch server will not be recognized as a proxy server.

[NOTE]
====
The following procedure outlines a standard configuration with two zones.
Adjust it to suit your own environment.
====

Zone 1 is a regular domain zone.
Its main purpose is to resolve saltboot hostnames such as TFTP, FTP, or Salt.
It can also resolve the terminal names if configured.

Zone 2 is the reverse zone of Zone 1.
Its main purpose is to resolve IP addresses back to hostnames.
Zone 2 is primarily needed for the correct determination of the FQDNs of the branch.

// REMARK: this procedure is probably too long.  Where to split?
// REMARK: are these list items (`*`) substeps?  Or what?  Confusing.
.Procedure: Configuring Bind with Two Zones

. Check the [systemitem]``Bind`` formula, click [btn]``Save``, and navigate to the menu:Formulas[Bind] tab.
. In the [guimenu]``Config`` section, select [systemitem]``Include Forwarders``.
. In the [guimenu]``Configured Zones`` section, use these parameters for Zone 1:
* In the [guimenu]``Name`` field, enter the domain name of your branch network  (for example: [systemitem]``branch1.example.com``).
* In the [guimenu]``Type`` field, select [systemitem]``master``.
. Click [btn]``Add item`` to add a second zone, and set these parameters for Zone 2:
* In the [guimenu]``Name`` field, use the reverse zone for the configured IP range (for example: [systemitem]``com.example.branch1``).
* In the [guimenu]``Type`` field, select [systemitem]``master``
. In the [guimenu]``Available Zones`` section, use these parameters for Zone 1:
* In the [guimenu]``Name`` field, enter the domain name of your branch network (for example: [systemitem]``branch1.example.org``).
* In the [guimenu]``File`` field, type the name of your configuration file.
. In the [guimenu]``Start of Authority (SOA)`` section, use these parameters for Zone 1:
* In the [guimenu]``Nameserver (NS)`` field, use the FQDN of the  branch server (for example: [systemitem]``branchserver.branch1.example.org``).
* In the [guimenu]``Contact`` field, use the email address for the domain administrator.
* Keep all other fields as their default values.
. In the [guimenu]``Records`` section, in subsection [guimenu]``A``, use these parameters to set up an A record for Zone 1:
* In the [guimenu]``Hostname`` field, use the hostname of the branch server (for example: [systemitem]``branchserver``).
* In the [guimenu]``IP`` field, use the IP address of the branch server (for example, [systemitem]``192.168.1.5``).
. In the [guimenu]``Records`` section, subsection [guimenu]``NS``, use these parameters to set up an NS record for Zone 1:
* In the input box, use the hostname of the branch server (for example: [systemitem]``branchserver``).
. In the [guimenu]``Records`` section, subsection [guimenu]``CNAME``, use these parameters to set up CNAME records for Zone 1:
* In the [guimenu]``Key`` field, enter [systemitem]``tftp``, and in the [guimenu]``Value`` field, type the hostname of the branch server (for example: [systemitem]``branchserver``).
* Click [guimenu]``Add Item``. In the [guimenu]``Key`` field, enter [systemitem]``ftp``, and in the [guimenu]``Value`` field, type the hostname of the branch server.
* Click [guimenu]``Add Item``. In the [guimenu]``Key`` field, enter [systemitem]``dns``, and in the [guimenu]``Value`` field, type the hostname of the branch server.
* Click [guimenu]``Add Item``. In the [guimenu]``Key`` field, enter [systemitem]``dhcp``, and in the [guimenu]``Value`` field, type the hostname of the branch server.
* Click [guimenu]``Add Item``. In the [guimenu]``Key`` field, enter [systemitem]``salt``, and in the [guimenu]``Value`` field, type the FQDN of the branch server (for example: [systemitem]``branchserver.branch1.example.org``).
. Set up Zone 2 using the same parameters as for Zone 1, but ensure you use the reverse details:
* The same SOA section as Zone 1.
* Empty A and CNAME records.
*  Additionally, configure in Zone 2:
** `Generate Reverse` field by the network IP address set in branch server network formula (for example, [systemitem]``192.168.1.5/24``).
** `For Zones` should specify the domain name of your branch network (for example, [systemitem]``branch1.example.org``).
. Click btn:[Save Formula] to save your configuration.
. Apply the highstate.


[IMPORTANT]
====
Reverse name resolution on terminals might not work for networks that are inside one of these IPv4 private address ranges:

* [systemitem]``10.0.0.0/8``
* [systemitem]``172.16.0.0/12``
* [systemitem]``192.168.0.0/16``

If you encounter this problem, go to the [guimenu]``Options`` section of the Bind formula, and click btn:[Add item]:

* In the [guimenu]``Options`` field, enter [systemitem]``empty-zones-enable``.
* In the [guimenu]``Value`` field, select [systemitem]``No``.
====
