# Makefile for src
#

# what is the backend top dir
TOP     = ..

# Specific stuff
SUBDIR		= susemanager

SPACEWALK_FILES		= mgr_ncc_sync_lib _init__ \
                          suseLib mgr_register

include $(TOP)/Makefile.defs
