#!/usr/bin/python -u
# -*- coding: utf-8 -*-
#
# Copyright (c) 2010 Novell
# Copyright (c) 2015 SUSE LLC
#
# This software is licensed to you under the GNU General Public License,
# version 2 (GPLv2). There is NO WARRANTY for this software, express or
# implied, including the implied warranties of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
# along with this software; if not, see
# http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
#

import os
import sys
from spacewalk.common.rhnLog import log_debug

if __name__ == '__main__':
    log_debug(2, "Not yet supported with SCC backend")
    sys.exit(0)

