#!/bin/bash
#
# Monitoring   Startup script for Monitoring Scout
#
# chkconfig: - 86 14
# description: NOCpulse Monitoring Scout

### BEGIN INIT INFO
# Provides: MonitoringScout
# Required-Start: $local_fs $network $named $time Monitoring
# Should-Start:   httpd
# Required-Stop: $local_fs $network $named $time Monitoring
# Should-Stop:   httpd
# Default-Start: 3 5
# Default-Stop: 0 1 6
# Short-Description: NOCpulse Monitoring Scout
# Description: NOCpulse MonitoringScout
### END INIT INFO

IDENTITY="/var/lib/nocpulse/.ssh/nocpulse-identity"
if [ ! -f "$IDENTITY" ]
then
    /bin/su -s /bin/bash -c "/usr/bin/ssh-keygen -q -t dsa -N '' -f $IDENTITY" - nocpulse
fi

/usr/sbin/MonitoringScout $@

