#!/bin/bash
#
# Monitoring   Startup script for Monitoring
#
# chkconfig: - 85 16
# description: NOCpulse Monitoring

### BEGIN INIT INFO
# Provides: Monitoring
# Required-Start: $local_fs $network $remote_fs
# Should-Start:   $syslog $named $time oracle-xe
# Required-Stop: $local_fs $network $remote_fs 
# Should-Stop:   $syslog $named $time oracle-xe
# Default-Start: 3 5
# Default-Stop: 0 1 6
# Short-Description: NOCpulse Monitoring
# Description: NOCpulse Monitoring 
### END INIT INFO

IDENTITY="/var/lib/nocpulse/.ssh/nocpulse-identity"
if [ ! -f "$IDENTITY" ]
then
    /bin/su -s /bin/bash -c "/usr/bin/ssh-keygen -q -t dsa -N '' -f $IDENTITY" - nocpulse
fi

/usr/sbin/Monitoring $@

