FROM opensuse/grafana:11.5.1

ENV GF_PATHS_PROVISIONING=/etc/grafana/provisioning
ENV GF_AUTH_ANONYMOUS_ENABLED=true
ENV GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

RUN grafana-cli plugins install yesoreyeram-infinity-datasource

CMD [ "run.sh" ]
