# Container used to run unit tests with Java 8
# VERSION 0.1

FROM suma-head-pgsql
MAINTAINER Johannes Renner "jrenner@suse.de"

# Install the required packages
ADD swap-java.sh /root/swap-java.sh
RUN /root/swap-java.sh

