#!/bin/bash

# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

if [ $UID != "0" ]; then
  echo "ERROR: must be root to execute"
  exit 1
fi

BACKEND=$( spacewalk-cfg-get db_backend )

if [ $BACKEND == 'postgresql' ]; then
	echo 'show server_encoding; show client_encoding;' | spacewalk-sql --select-mode -
else
	echo "Unknown database backend [$BACKEND]"
	exit 1
fi

