#!/bin/bash

function usage {
    cat << EOF
usage: $0 options

    Check the disk space available for the configured directories

OPTIONS:
    -h              Show this message
EOF
}

function parseArguments {
    while getopts "h?c" opt; do
        case "$opt" in
            h|\?)
                usage
                exit 0
                ;;
        esac
    done
}

function parseConfiguration {
    if [ -f $1 ]; then
        DISKCHECKDIRS=`grep ^[[:blank:]]*spacecheck_dirs $1 | sed -e "s/.*=[[:blank:]]*//"`
        DISKCHECKALERT=`grep ^[[:blank:]]*spacecheck_free_alert $1 | sed -e "s/.*=[[:blank:]]*//"`
        DISKTHRESHOLD=`grep ^[[:blank:]]*spacecheck_free_critical $1 | sed -e "s/.*=[[:blank:]]*//"`
        DISKCHECKSHUTDOWN=`grep ^[[:blank:]]*spacecheck_shutdown $1 | sed -e "s/.*=[[:blank:]]*//"`
    fi

    if [ "$DISKCHECKDIRS" = "" ]; then
        DISKCHECKDIRS="/var/spacewalk /var/cache /srv"
    fi
    if [ "$DISKCHECKALERT" = "" ] || [ "$DISKCHECKALERT" -gt 90 ]; then
        DISKCHECKALERT=10
    fi
    if [ "$DISKTHRESHOLD" = "" ] || [ "$DISKTHRESHOLD" -ge "$DISKCHECKALERT" ]; then
        DISKTHRESHOLD=$(($DISKCHECKALERT / 2))
    fi
    if [ "$DISKCHECKSHUTDOWN" = "" ]; then
        DISKCHECKSHUTDOWN=true
    fi
}

function ensureSpacewalkRunning {
    systemctl status spacewalk.target > /dev/null 2>&1
    if [ $? != 0 ]; then
        echo  "DISKCHECK: spacewalk services are not running - skipping disk check."
        exit 0
    fi
}

function updateSeverity {
    if [ $1 -gt $CHECKSEVERITY ]; then
        CHECKSEVERITY=$1
    fi
}

# Main script

CHECKONLY=false
STOPCHECK=0
CHECKSEVERITY=0

ensureSpacewalkRunning

parseArguments "$@"
parseConfiguration /etc/rhn/rhn.conf

for DIR in $DISKCHECKDIRS
do
    if [ ! -d $DIR ]; then
        updateSeverity 1
        continue
    fi

    USEDSPACE=`df -PH $DIR | tail -1 | awk '{print $5}' | sed -e"s/\%//"`
    FREESPACE=$((100 - $USEDSPACE))
    if [ $FREESPACE -lt $DISKTHRESHOLD ] && [ "$STOPCHECK" = "0" ]; then
        if [ "$DISKCHECKSHUTDOWN" = true ]; then
            updateSeverity 3
        else
            updateSeverity 3
        fi

        STOPCHECK=1
        break
    elif [ $FREESPACE -lt $DISKCHECKALERT ] && [ "$STOPCHECK" = "0" ]; then
        updateSeverity 2
    fi
done

if [ "$CHECKONLY" = false ] && [ "$STOPCHECK" = "1" ] && [ "$DISKCHECKSHUTDOWN" = true ]; then
    spacewalk-service stop
    echo "DISKCHECK CRITICAL: spacewalk shut down"
fi

exit $CHECKSEVERITY
