export default {
  "admin/config/monitoring": () => import("./config/monitoring.renderer"),
  "admin/setup/products/products": () => import("./setup/products/products"),
  "admin/task-engine-status/taskotop": () => import("./task-engine-status/taskotop"),
  "admin/setup/list-payg": () => import("./list-payg/list-payg.renderer"),
  "admin/setup/payg": () => import("./payg/payg.renderer"),
  "admin/setup/create-payg": () => import("./create-payg/create-payg.renderer"),
  "admin/config/password-policy": () => import("./password-policy/password-policy.renderer"),
  "admin/config/access-group": () => import("./access-group/access-group.renderer"),
  "admin/setup/proxy": () => import("./setup/proxy/proxy.renderer"),
  "admin/hub/register-peripheral": () => import("./hub/register-peripheral.renderer"),
  "admin/hub/migrate-from-v1": () => import("./hub/migrate-from-v1.renderer"),
  "admin/hub/migrate-from-v2": () => import("./hub/migrate-from-v2.renderer"),
  "admin/hub/list-tokens": () => import("./hub/list-tokens.renderer"),
  "admin/hub/hub-details": () => import("./hub/hub-details.renderer"),
  "admin/hub/peripherals": () => import("./hub/peripherals.renderer"),
  "admin/hub/peripherals/:id": () => import("./hub/peripheral-details.renderer"),
  "admin/hub/peripherals/:id/sync-channels": () => import("./hub/sync-channels.renderer"),
};
