import type { Meta, StoryObj } from "@storybook/react-webpack5";

import { StoryRow, StripedStorySection } from "manager/storybook/layout";

import {
  ActionChainLink,
  ActionLink,
  ChannelAnchorLink,
  ChannelLink,
  PackageLink,
  SystemGroupLink,
  SystemLink,
} from "./links";

const meta = {
  title: "Components/Navigation/Links",
  component: ChannelLink,
  parameters: {
    docs: {
      description: {
        component:
          "Link helpers that build the canonical Uyuni URL for a channel, action, system, action chain, system group, or package.",
      },
    },
  },
  args: {
    id: 42,
    children: "Example channel",
    newWindow: false,
    className: "",
    title: "Open channel details",
  },
  argTypes: {
    id: {
      control: "text",
      description: "Entity identifier inserted into the generated Uyuni URL.",
      table: { type: { summary: "string | number" } },
    },
    newWindow: {
      control: "boolean",
      description: "Opens the target in a new window and adds `noopener noreferrer` when enabled.",
      table: { type: { summary: "boolean" }, defaultValue: { summary: "false" } },
    },
    children: {
      control: "text",
      description: "Visible content of link variants that accept children.",
      table: { type: { summary: "ReactNode" } },
    },
    className: {
      control: "text",
      description: "Additional CSS classes supported by the action, system, chain, group, and package links.",
      table: { type: { summary: "string" } },
    },
    title: {
      control: "text",
      description: "Optional native tooltip text supported by `ChannelLink`.",
      table: { type: { summary: "string" } },
    },
  },
} satisfies Meta<typeof ChannelLink>;

export default meta;

type Story = StoryObj<typeof meta>;

export const Playground: Story = {};

export const EntityLinks: Story = {
  render: () => (
    <StripedStorySection>
      <StoryRow>
        <ChannelLink id={101}>Channel</ChannelLink>
        <ChannelAnchorLink id={101} title="Channel permalink" />
        <ActionLink id={202}>Action</ActionLink>
        <SystemLink id={303}>System</SystemLink>
        <ActionChainLink id={404}>Action chain</ActionChainLink>
        <SystemGroupLink id={505}>System group</SystemGroupLink>
        <PackageLink id={606}>Package</PackageLink>
      </StoryRow>
    </StripedStorySection>
  ),
  parameters: {
    controls: { disable: true },
    docs: { description: { story: "Every entity-specific link generated by this module." } },
  },
};

export const NewWindow: Story = {
  args: {
    newWindow: true,
    children: "Channel in a new window",
  },
};
