# Makefile for mgr-register
#

# what is the backend top dir
TOP     = ..

# Specific stuff
SUBDIR		= susemanager

SPACEWALK_FILES		= __init__ \
		  suseLib mgr_register

include $(TOP)/Makefile.defs
