# Makefile for the action handlers module
#

TOP	= ../..
SUBDIR	= server/action_extra_data

SPACEWALK_FILES	= __init__ configfiles kickstart kickstart_guest packages errata hardware reboot \
          rollback up2date_config script rhn_applet kickstart_host image \
          distupgrade clientcert

include $(TOP)/Makefile.defs

