# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the xmlrpc handlers
#

TOP	= ../..
SUBDIR	= upload_server/handlers

FILES	= __init__

SUBDIRS = package_push

include $(TOP)/Makefile.defs

