# Makefile for the action handlers module
#

TOP	= ../..
SUBDIR	= server/action

SPACEWALK_FILES	= __init__ configfiles kickstart kickstart_guest packages errata hardware reboot \
          rollback activation script rhn_applet kickstart_host \
          utils image distupgrade clientcert channels

include $(TOP)/Makefile.defs

