# Makefile for suseRegister
#

ROOT	?= $(shell python -c "from distutils.sysconfig import get_python_lib; print get_python_lib()")
SUBDIR	= suseRegister
FILES	= __init__ info

# what is the backend top dir
TOP     = ..
include $(TOP)/Makefile.defs
