/*
 * Copyright (c) 2026 SUSE LLC
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 */

package com.suse.coco.module.pvattest;

import com.suse.coco.module.AttestationModule;
import com.suse.coco.module.AttestationWorker;

import java.util.List;

/**
 * Module description for Pvattest
 */
public class PvattestModule implements AttestationModule {

    /**
     * Result type for report generated by Pvattest
     */
    public static final int IBM_PVATTEST = 3;

    @Override
    public String getName() {
        return PvattestModule.class.getName();
    }

    @Override
    public int getSupportedType() {
        return IBM_PVATTEST;
    }

    @Override
    public AttestationWorker getWorker() {
        return new PvattestWorker();
    }

    @Override
    public List<String> getAdditionalMappers() {
        return List.of("mappers/pvattest.xml");
    }
}
