.TH susemanagerproxy-plugin "8" "04 Apr 2013" "susemanager-plugin" "Support Utilities Manual"
.SH NAME
susemanagerproxy-plugin \- SUSE Manager Proxy Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include
SUSE Manager Proxy information. Supportconfig saves the plugin output as plugin-susemanagerproxy.txt.

.SH FILES
.I /usr/lib/supportconfig/plugins/susemanagerproxy
.RS
The SUSE Manager Proxy plugin
.RE
.SH AUTHOR
Michael Calmer <Michael.Calmer@suse.com>
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
