[[client-cfg-autoinstallation-methods]]
= Introduction


{ay} and Kickstart configuration files allow you to automate client system installations.
This is useful if you need to install a large number of clients.

For {sle} clients, use {ay}.
When you have created an {ay} file, you can upload and manage it using the {productname} {webui}.

For {rhel} clients, use Kickstart.
Kickstart files are created, modified, and managed within the {productname} {webui}.

We recommend that you use PXE boot for installing clients.
PXE booting requires a DHCP server that points to your {productname} Server.
The {productname} Server then acts as a TFTP server.

The TFTP environment is generated with Cobbler.
Cobbler can also generate a bootable ISO image.
The ISO image can be used to install machines when PXE boot is not an option; for more information, see xref:client-configuration:cobbler.adoc[].
// Cobbler allows you to automate bare-metal installations.
// It uses DHCP to access a PXE boot server, and can be used in virtualized environments.
