[[client-cfg-autoinstallation-autoyast]]
= AutoYaST

When you install a {sle} client, there are a number of questions you need to answer.
To automate installation, you can create an {ay} file with all the answers to those questions, so that no user intervention is required.

{ay} files can be kept on a server and read by individual clients during installation.
The same {ay} file is used to install multiple clients.

{ay} can be used to schedule a registered system to be installed with a new operating system and package profile, or you can use it to install a new system that was not previously registered, or does not yet have an operating system installed.

For more information about {ay}, see https://doc.opensuse.org/projects/autoyast/.

////
This is general autoyast info, not specific to SUMA. LKB 2019-07-29

When a machine is to receive a network-based {ay} installation, the following events must occur in this order:

. After being connected to the network and turned on, the machine's PXE logic broadcasts its MAC address and requests to be discovered.
. If no static IP address is used, the DHCP server recognizes the discovery request and offers network information needed for the new machine to boot. This includes an IP address, the default gateway to be used, the netmask of the network, the IP address of the TFTP or HTTP server holding the bootloader program, and the full path and file name to that program (relative to the server's root).
. The machine applies the networking information and initiates a session with the server to request the bootloader program.
. The bootloader searches for its configuration file on the server from which it was loaded. This file dictates which Kernel and Kernel options, such as the initial RAM disk (initrd) image, should be executed on the booting machine. Assuming the bootloader program is SYSLINUX, this file is located in the [path]``pxelinux.cfg`` directory on the server and named the hexadecimal equivalent of the new machine's IP address. For example, a bootloader configuration file for {sles} should contain:
+

----
port 0
prompt 0
timeout 1
default autoyast
label autoyast
  kernel vmlinuz
  append autoyast=http://`my_susemanager_server`/`path`\
    install=http://`my_susemanager_server`/`repo_tree`
----
. The machine accepts and uncompresses the initrd and kernel, boots the kernel, fetches the instsys from the install server and initiates the {ay} installation with the options supplied in the bootloader configuration file, including the server containing the {ay} configuration file.
. The new machine is installed based on the parameters established within the {ay} configuration file.
////



== Before you Begin

Some preparation is required for your infrastructure to handle {ay} installations.
Before you create an {ay} profile, consider:

* A DHCP server is not required for {ay}, but it can make things easier.
If you are using static IP addresses, you should select static IP while developing your {ay} profile.
* Host the {ay} distribution trees via HTTP, provided by {productname}.
* If you are performing a bare metal {ay} installation, use these settings:
** Configure DHCP to assign the required networking parameters and the bootloader program location.
** In the bootloader configuration file, specify the kernel and appropriate kernel options to be used.



== Build a Bootable ISO

You will need to create a bootable ISO image to be used by the target system for installation.
When the system is rebooted or switched on, it boots from the image, loads the {ay} configuration from your {productname}, and installs {sles} according to the {ay} profile.

To use the ISO image, boot the system and type `autoyast` at the prompt (assuming you left the label for the {ay}  boot as ``autoyast``).
Press kbd:[Enter] to begin the {ay}  installation.

This is managed by the KIWI image system.
For more information about KIWI, see http://doc.opensuse.org/projects/kiwi/doc/.



== Integrate with PXE

Instead of using a bootable ISO image, you can use a PXE image instead.
This is less error-prone, allows {ay} installation from bare metal, and integrates with existing PXE/DHCP environments.

To use this method, make sure your systems have network interface cards (NICs) that support PXE.
You will need to install and configure a PXE server, ensure DHCP is running, and place the installation repository on an HTTP server that is reachable by the {productname} Server.

Upload the {ay} profile to the {productname} Server using the {productname} {webui}.

When the {ay} profile has been created, use the URL from the [guimenu]``Autoinstallation Overview`` page as the image location.

For more information about PXE boot, see https://documentation.suse.com/sles/15-SP1/html/SLES-all/cha-deployment-prep-pxe.html

For more information about autoinstallation profiles, see xref:reference:systems/autoinst-profiles.adoc[].
