{
 "title": "Uyuni Server with logs",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "query": "mgr-server" }
  ]
 },
 "panels": [
  {
   "title": "Uyuni and Salt Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Salt Jobs in last 24 hrs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salt_jobs{fun=~\".+\"}",
     "legendFormat": "{{fun}}"
    }
   ]
  },
  {
   "title": "Salt \"state.apply\" in last 24 hrs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salt_jobs{fun=~\"state.apply.*\"}",
     "legendFormat": "{{fun}}"
    }
   ]
  },
  {
   "title": "Packages Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_packages_total\"}",
     "legendFormat": "total packages"
    }
   ]
  },
  {
   "title": "Channels Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_channels_total\"}",
     "legendFormat": "channels total"
    }
   ]
  },
  {
   "title": "Total Actions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_actions_total\"}",
     "legendFormat": "total actions"
    }
   ]
  },
  {
   "title": "Pending Actions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_actions_pending_total\"}",
     "legendFormat": "pending actions"
    }
   ]
  },
  {
   "title": "Actions Total in last 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_actions_last_24hours_total\"}",
     "legendFormat": "actions total in last 24 hours"
    }
   ]
  },
  {
   "title": "Completed Actions in last 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_actions_completed_last_24hours_total\"}",
     "legendFormat": "compelted actions in last 24 hours"
    }
   ]
  },
  {
   "title": "Failed Actions in last 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_actions_failed_last_24hours_total\"}",
     "legendFormat": "failed actions in last 24 hours"
    }
   ]
  },
  {
   "title": "Salt Jobs Total in last 24h",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(salt_jobs)",
     "legendFormat": "salt jobs total in last 24 hours"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors in logs over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": " sum by (job) (count_over_time({job=~\".+\"} |~ `(?i)error|(?i)severe|(?i)critical|(?i)fatal` [$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Errors logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{job=~\".+\"} |~ `(?i)error|(?i)severe|(?i)critical|(?i)fatal`"
    }
   ]
  }
 ]
}