{
 "title": "Supportconfig with Logs",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Component",
    "label": "Server component",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Uyuni and Salt Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Salt Jobs in last 24 hrs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(fun) (salt_jobs{fun=~\".+\"})",
     "legendFormat": "{{fun}}"
    }
   ]
  },
  {
   "title": "Salt Master Configuration",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "salt_master_config", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Salt \"state.apply\" in last 24 hrs",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "salt_jobs{fun=~\"state.apply.*\"}",
     "legendFormat": "{{fun}}"
    }
   ]
  },
  {
   "title": "Salt Keys",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "salt_keys", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Total Salt Jobs last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(salt_jobs)",
     "legendFormat": "salt jobs total in last 24 hours"
    }
   ]
  },
  {
   "title": "Completed Actions in last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_actions_completed_last_24hours_total\"}",
     "legendFormat": "compelted actions in last 24 hours"
    }
   ]
  },
  {
   "title": "Failed Actions in last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_actions_failed_last_24hours_total\"}",
     "legendFormat": "failed actions in last 24 hours"
    }
   ]
  },
  {
   "title": "Actions Total in last 24h",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uyuni_summary{name=\"uyuni_summary_actions_last_24hours_total\"}",
     "legendFormat": "actions total in last 24 hours"
    }
   ]
  },
  {
   "title": "Logs and Errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Errors in logs over time",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": " sum by (job) (count_over_time({job=~\"$Component\"} |~ `(?i)error|(?i)severe|(?i)critical|(?i)fatal` [$__interval]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Errors logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{job=~\"$Component\"} |~ `(?i)error|(?i)severe|(?i)critical|(?i)fatal`"
    }
   ]
  }
 ]
}