#!/bin/bash

export UYUNI_PROJECT=uyuni-project
export UYUNI_VERSION=master

set -x
set -e

./00_setup_env.sh
./01_setup_tmp_dirs.sh
./02_setup_network.sh
./03_run_controller.sh
./04_setup_ssh_controller.sh
./05_install_gems_in_controller.sh
./06_start_server.sh
./07_manager_setup.sh
./08_build_server_code.sh
./09_run_sshminion.sh
./10_setup_sshd.sh
./11_run_core_tests.sh
./12_run_salt_sle_minion.sh
./13_run_salt_rhlike_minion.sh
./14_run_salt_deblike_minion.sh
./15_accept_all_keys.sh
./16_run_init_clients_tests.sh
./17_run_secondary_tests.sh

