/*
 * Copyright (c) 2024 SUSE LLC
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 *
 * Red Hat trademarks are not licensed under GPLv2. No permission is
 * granted to use or replicate Red Hat trademarks that are incorporated
 * in this software or its documentation.
 */

package com.suse.cloud;

import com.google.gson.annotations.SerializedName;

import org.apache.commons.lang3.builder.EqualsBuilder;
import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.commons.lang3.builder.ToStringBuilder;

import java.time.Instant;

/**
 * Simple POJO with the compliance information as parsed from the JSON generated by the external PAYG data extractor.
 */
public class PaygComplainceInfo {

    @SerializedName("isPaygInstance")
    private final boolean paygInstance;

    private final boolean compliant;

    private final CloudProvider cloudProvider;

    @SerializedName("hasModifiedPackages")
    private final boolean anyPackageModified;

    private final boolean billingAdapterRunning;

    @SerializedName("billingServiceStatus")
    private final boolean billingAdapterHealthy;

    private final long timestamp;

    /**
     * Creates the compliance info for a BYOS instance.
     */
    public PaygComplainceInfo() {
        // By default, assume it's a compliant BYOS instance
        this(CloudProvider.None, false, false, true, true);
    }

    /**
     * Creates the compliance info for an instance.
     * @param provider the cloud provider
     * @param isPayg if the instance is PAYG
     * @param hasModifiedPackages if some packages are modified
     * @param isAdapterRunning if the required billing adapter service is running
     * @param isAdapterHealthy if the required billing adapter service is healthy. The value is forced to
     * <code>false</code> when the other parameter <code>isAdapterRunning</code> is set to false.
     */
    public PaygComplainceInfo(CloudProvider provider, boolean isPayg, boolean hasModifiedPackages,
                              boolean isAdapterRunning, boolean isAdapterHealthy) {
        paygInstance = isPayg;

        cloudProvider = provider;
        anyPackageModified = hasModifiedPackages;
        billingAdapterRunning = isAdapterRunning;
        billingAdapterHealthy = isAdapterRunning && isAdapterHealthy;

        // Set the compliant flag accordingly to the value received
        compliant = billingAdapterRunning && billingAdapterHealthy && !anyPackageModified;

        timestamp = Instant.now().getEpochSecond();
    }

    public boolean isPaygInstance() {
        return paygInstance;
    }

    public boolean isCompliant() {
        return compliant;
    }

    public CloudProvider getCloudProvider() {
        return cloudProvider;
    }

    public boolean isAnyPackageModified() {
        return anyPackageModified;
    }

    public boolean isBillingAdapterRunning() {
        return billingAdapterRunning;
    }

    public boolean isBillingAdapterHealthy() {
        return billingAdapterHealthy;
    }

    public Instant getTimestamp() {
        return Instant.ofEpochSecond(timestamp);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }

        if (!(o instanceof PaygComplainceInfo)) {
            return false;
        }

        PaygComplainceInfo that = (PaygComplainceInfo) o;
        return new EqualsBuilder()
            .append(paygInstance, that.paygInstance)
            .append(compliant, that.compliant)
            .append(anyPackageModified, that.anyPackageModified)
            .append(billingAdapterRunning, that.billingAdapterRunning)
            .append(billingAdapterHealthy, that.billingAdapterHealthy)
            .append(timestamp, that.timestamp)
            .append(cloudProvider, that.cloudProvider)
            .isEquals();
    }

    @Override
    public int hashCode() {
        return new HashCodeBuilder(17, 37)
            .append(paygInstance)
            .append(compliant)
            .append(cloudProvider)
            .append(anyPackageModified)
            .append(billingAdapterRunning)
            .append(billingAdapterHealthy)
            .append(timestamp)
            .toHashCode();
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this)
            .append("paygInstance", isPaygInstance())
            .append("compliant", isCompliant())
            .append("cloudProvider", getCloudProvider())
            .append("anyPackageModified", isAnyPackageModified())
            .append("billingAdapterRunning", isBillingAdapterRunning())
            .append("billingAdapterHealthy", isBillingAdapterHealthy())
            .append("timestamp", getTimestamp())
            .toString();
    }
}
