[[software.mgmt.repos]]
= Manage Repositories

== Repositories

Add or manage custom or third-party package repositories and link the repositories to an existing channel.
The repositories feature currently supports repomd repositories.

To create a new repository click the [guimenu]``Create Repository`` link at the top right of the [guimenu]``Manage Repositories`` page.
The [guimenu]``Create Repository`` screen prompts you to enter a [guimenu]``Repository Label`` such as `sles-12-x86_64` and a [guimenu]``Repository URL``.
You may enter URLs pointing to mirror lists or direct download repositories, then click btn:[Create Repository].
Select the desired SSL certificate of authority, client certificate and key from the drop down list.
SSL keys should be placed in ``http://EXAMPLE-FQDN.com/pub``.

To link the new repository to an existing software channel, select [guimenu]``Manage Software Channels`` from the left menu, then click the channel you want to link.
In the channel's detail page, click the [guimenu]``Repositories`` subtab, then check the box next to the repository you want to link to the channel.
Click btn:[Update Repositories].

To synchronize packages from a custom repository to your channel, click the [guimenu]``Sync`` link from the channel's [guimenu]``Repositories`` subtab, and confirm by clicking the btn:[Sync] button.

You can also perform a synchronization via command line by using the [command]``spacewalk-repo-sync`` command, which additionally allows you to accept keys.

[command]``spacewalk-repo-sync`` creates log files in the [path]``/var/log/rhn/reposync`` directory. {productname} uses one log file per channel and reuses it with the next synchronization run.
