[[install-vm]]
= Install SUSE Manager in a Virtual Machine Environment with JeOS



[[quickstart.sect.kvm.settings]]
== Virtual Machine Manager (virt-manager) Settings

This chapter provides the required (KVM) settings for installation of {sle} Just Enough Operating System (JeOS) 15 as the base for {productname}.
A kernel virtual machine (KVM) combined with Virtual Machine Manager (_virt-manager_) will be used as a sandbox for this installation.

// This section needs revision its still ugly (LKB, KE), but now updated (KE)
// - 2019-06-19.

Enter the following settings when creating a new virtual machine using *virt-manager*.

[NOTE]
====
This table specifies the minimum requirements.
These are suitable for a quick test installation, such as a server with one client.
If you want to use a production environment, review the requirements listed in xref:hardware-requirements.adoc[].
====

In the following table replace _version_ with the actual product version string.
Find the JeOS image at https://download.suse.com/.

[cols="1,1", options="header"]
|===
2+<| KVM Settings
| Installation Method | Import Existing Disk Image
| OS:                 | Linux
| Version:            | SLES_version_-JeOS-for-kvm-and-xen.x86_64-GM.qcow2
| Memory:             | 8192 MB
| CPU's:              | 4
| Storage Format:     | _.qcow2_ 24 GB (Default) JeOS Root Partition
| Virtual Disks:      |
| VirtIO Disk 2       | 101 GB for [path]``/var/spacewalk``
| VirtIO Disk 3       | 50 GB for [path]``/var/lib/pgsql``
| VirtIO Disk 4       | 4 GB for swap
| Name:               | test-setup
| Network             | Bridge _br0_
|===

.{sle} Virtualization Guide
[NOTE]
====
For more information on virtualization, see https://documentation.suse.com/sles/15-SP1/html/SLES-all/book-virt.html.
====



[[jeos.kvm.settings]]
== JeOS KVM Settings

Create three additional virtual disks required for the {productname} storage partitions.

.Procedure: Creating the Required Partitions with KVM
. Create a new virtual machine using the downloaded JeOS KVM image and select [guimenu]``Import existing disk image``.
. Configure RAM and number of CPUs (at least 8 GB RAM and 4 CPUs).
. Name your KVM machine and select the [guimenu]``Customize configuration before install`` check box.
. Click btn:[Add Hardware] to create three new virtual disks with these specifications.
These disks will be partitioned and mounted in <<proc.jeos.susemgr.prep>>.
+

[NOTE]
====
Storage size values are the absolute minimum—only suitable for a small test or demo installation.
Especially [path]``/var/spacewalk/`` may quickly need more space.
Also consider to create a separate partition for [path]``/srv`` where Kiwi images are stored.
====
+

[cols="1,1,1", options="header"]
|===
| VirtIO Storage Disks | Name      | Sizing
| VirtIO Disk 2        | spacewalk | 101{nbsp}GB
| VirtIO Disk 3        | pgsql     | 50{nbsp}GB
| VirtIO Disk 4        | swap      | 4{nbsp}GB
|===

. Click btn:[Begin Installation] to boot the new VM from the JeOS image.

Follow the prompts to complete the basic JeOS installation, until the process is complete and the command prompt waits for input.

During the basic installation prompts you are asked to enter the root password.
In the next message box click btn:[Confirm root Password].



[[jeos.susemgr.prep]]
== Preparing JeOS for SUSE Manager

[[proc.jeos.susemgr.prep]]
.Procedure: Preparing JeOS for {productname} Installation

// Most steps are currently needed because of 4.0 workarounds
. Log in as `root`.

. Uninstall the `sles-release` package:
+

----
rpm -e --nodeps sles-release
----

. Register {productname} with SCC (for example, replace `<productnumber>` with `{productnumber}` and `<architecture>` with `x86_64`):
+

----
SUSEConnect -e<EMAIL_ADDRESS> -r<SUSE_MANAGER_CODE> \
  -p SUSE-Manager-Server/<productnumber>/<architecture>
----

. Add {productname} repositories:
+

----
SUSEConnect -p sle-module-basesystem/15.1/x86_64
SUSEConnect -p sle-module-python2/15.1/x86_64
SUSEConnect -p sle-module-server-applications/15.1/x86_64
SUSEConnect -p sle-module-web-scripting/15.1/x86_64
SUSEConnect -p sle-module-suse-manager-server/<productnumber>/x86_64
----
+
JeOS is configured to install only required packages.
To get all features working you should allow to install also recommended packages.
In `/etc/zypp/zypp.conf` change:
+

----
solver.onlyRequires = true
----
+

To:
+
----
solver.onlyRequires = false
----

. Install [package]#yast2-storage-ng# with all required dependencies (approx. 40 packages, 30 MB when installed).
This basic administration package is required for preparing storage partitions:
+

----
zypper in yast2-storage-ng
----
. Partition and mount the virtual disks at the following locations using {yast} Partitioner ([command]``yast2 disk``).
+

[NOTE]
====
Storage size values are the absolute minimum.
They are suitable only for a small test or demonstration installation, such as a server with one client.
Especially [path]``/var/spacewalk/`` may quickly need more space.
Also consider to create a separate partition for [path]``/srv`` where Kiwi images are stored.
====

[cols="1,1,1,1", options="header"]
|===
| VirtIO Storage Disks | Name                     | Storage Size | File System Type
| VirtIO Disk 2        | [path]``/var/spacewalk`` | 101{nbsp}GB  | XFS
| VirtIO Disk 3        | [path]``/var/lib/pgsql`` | 50{nbsp}GB   | XFS
| VirtIO Disk 4        | [path]``swap``           | 4{nbsp}GB    | swap
|===

. Exit the partitioner and install the {productname} pattern (approximately 730 packages, using 1.4 GB of disk space when installed):
+

----
zypper in -t pattern suma_server
----

. Reboot.

For proceeding with {productname} setup, see xref:installation:server-setup.adoc[SUSE Manager Setup].
