#!/bin/bash
if [[ $1 == "status" || $1 == "enable" || $1 == "disable" ]]; then
	[[ -z $2 ]] && PILLAR="" || PILLAR="pillar=$2"
	/usr/bin/salt-call --out=json --log-level=error --local --file-root=/usr/share/susemanager/salt state.apply srvmonitoring.$1 $PILLAR
elif  [[ $1 == "--help" ]]; then
  echo "${0} {enable|status|disable} [pillar_data]"
else
	echo "Invalid argument. Try --help."
fi
exit 0
