alter table rhn_url_probe_step alter column recid type numeric(12);
alter table rhn_url_probe_step alter column url_probe_id type numeric(12);
alter table rhn_url_probe_step alter column step_number type numeric(3);
alter table rhn_url_probe_step alter column trans_warn type numeric(12);
alter table rhn_url_probe_step alter column trans_crit type numeric(12);
alter table rhn_url_probe_step alter column through_warn type numeric(12);
alter table rhn_url_probe_step alter column through_crit type numeric(12);
alter table rhn_url_probe_step alter column cookie_port type numeric(5);
alter table rhn_url_probe_step alter column cookie_maxage type numeric(9);
