# Container used to test java code of SUSE Manager
#
# VERSION               0.2
FROM PARENT_CONTAINER
MAINTAINER Johannes Renner "jrenner@suse.de"

# Make sure the package repository is up to date
RUN zypper --non-interactive --gpg-auto-import-keys ref

# Install needed packages
RUN zypper in -y ant ant-junit apache-ivy java-1_6_0-ibm-devel python spacewalk-backend-sql-postgresql spacewalk-setup spacewalk-setup-postgresql sudo susemanager-tools tar

# Extract data for mgr-ncc-sync
ADD UC5.tar.bz2 /root/UC5.tar.bz2
RUN cd /root; tar xvjf UC5.tar.bz2
RUN rm /root/UC5.tar.bz2
