#!/bin/sh
SEARCH_LIBRARY_PATH="/usr/lib:/usr/lib64:/usr/lib/oracle/11.2/client64/lib:/usr/lib/oracle/11.2/client/lib:/usr/lib/gcj/postgresql-jdbc:/usr/lib64/gcj/postgresql-jdbc"
SEARCH_RHN_CLASSPATH="/usr/share/rhn/classes:/usr/share/nutch-core:/usr/share/nutch-core/conf"
SEARCH_RHN_JARS="/usr/share/rhn/lib/spacewalk-asm.jar:/usr/share/rhn/lib/rhn.jar:/usr/share/rhn/lib/java-branding.jar"
SEARCH_JARS="/usr/share/rhn/search/lib/*"
SEARCH_INIT_MEMORY=32
SEARCH_MAX_MEMORY=96
SEARCH_CLASSPATH="${SEARCH_JARS}:${SEARCH_RHN_CLASSPATH}:${SEARCH_RHN_JARS}"
#SEARCH_PARAMS="-Dibm.dst.compatibility=true -Dfile.encoding=UTF-8 -Xms${SEARCH_INIT_MEMORY}m -Xmx${SEARCH_MAX_MEMORY}m"
SEARCH_PARAMS="-Dfile.encoding=UTF-8 -Xms${SEARCH_INIT_MEMORY}m -Xmx${SEARCH_MAX_MEMORY}m"

JAVACMD="/usr/bin/java -Djava.library.path=${SEARCH_LIBRARY_PATH} -classpath ${SEARCH_CLASSPATH} ${SEARCH_PARAMS}"

if [[ $# -eq 0 ]]; then
    $JAVACMD com.redhat.satellite.search.Main
else
    case $1 in 
        'cleanindex')
        systemctl stop rhn-search
        $JAVACMD com.redhat.satellite.search.DeleteIndexes > /dev/null
        systemctl start rhn-search
        ;;
        *)
        echo "Invalid argument: To start the service use 'systemctl start rhn-search'... to clean the search indexes use 'rhn-search cleanindex'"
    esac
fi
