# Makefile for the rhnSQL module
#

TOP     = ../..
SUBDIR	= server/rhnSQL

SPACEWALK_FILES	= __init__ sql_base sql_lib \
	  sql_row sql_sequence sql_table sql_types \
          dbi driver_postgresql const

include $(TOP)/Makefile.defs
