name: Bug Report
description: File a bug report
labels: [bug, P5]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug report in [Uyuni](https://www.uyuni-project.org). Before you proceed, please ensure that there is no [issue](https://github.com/uyuni-project/uyuni/issues) for the bug yet.
  - type: textarea
    attributes:
      label: Problem description
      description: Include the expected and actual behavior. The more details, the better!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the issue
      description: Please explain the steps to reproduce the issue
      placeholder: "Steps to reproduce the issue\n1.\n2.\n3.\n"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Uyuni-tools version used to deploy/manage the server (or proxy)
      description: "Paste the output of `zypper info mgradm`, `zypper info mgrctl` (and `zypper info mgrpxy`, if you use a proxy)"
      render: bash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Uyuni server version
      description: "Paste the output of `mgrctl exec -t cat /etc/uyuni-release` and `podman images -f label=org.uyuni.version -f containers=true --digests`"
      render: bash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Uyuni proxy version (if used)
      description: "Paste the output of `podman images -f label=org.uyuni.version -f containers=true --digests`"
      render: bash
    validations:
      required: false
  - type: textarea
    attributes:
      label: Useful logs
      description: Do you see anything in the logs under `/var/log/rhn/` that looks like it could be related?
      placeholder: |
        Paste log excerpt
      render: bash
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: Is there any additional information that could help us understanding or fixing the issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for filling out this bug report!
