# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the xmlrpc handlers
#

TOP	= ../
SUBDIR	= upload_server

FILES	= __init__

SUBDIRS = handlers

include $(TOP)/Makefile.defs

