#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-Only

# we need to make sure there is correct access for our services

PGDATA="${PGDATA:-/var/lib/pgsql/data}"
HBA_FILE="${PGDATA}/pg_hba.conf"
CUSTOM_HBA_FILE="${PGDATA}/pg_hba_custom.conf"
NAMESPACE_FILE=/var/run/secrets/kubernetes.io/serviceaccount/namespace
PG_HBA_CHANGED=""

if [ -f "$NAMESPACE_FILE" ] ; then
    # kubernetes
    NAMESPACE=$(<"$NAMESPACE_FILE")

    # reverse lookup does nor work during initialization, we must check also IP
    POD_IP=$(getent hosts $(cat /etc/hostname) 2>/dev/null | sed 's/[[:space:]].*//')
    POD_NETWORK=$(echo "${POD_IP:-10.42.0.0}" | cut -d. -f1,2).0.0/16
    INTERNAL_ACCESS="$POD_NETWORK .$NAMESPACE.svc.cluster.local"

    # handle external access via traefik
    # it matches the IP so it must be rejected explicitly, by domain
    EXTERNAL_RULES="hostssl reportdb all .kube-system.svc.cluster.local scram-sha-256
host all all .kube-system.svc.cluster.local reject"
else
    # podman
    INTERNAL_ACCESS=uyuni-server
    EXTERNAL_RULES=""
fi

# Check if we already have the include directive
if [ -z "$(sed -n "/include_if_exists pg_hba_custom.conf/p" "$HBA_FILE")" ]; then
    # Capture existing content, excluding our legacy configuration
    # This preserves user-added rules and comments.
    S="[[:space:]]\{1,\}"
    CUSTOM_CONFIG=$(sed -e "/^local${S}all${S}all${S}peer/d" \
                        -e "/^local${S}replication${S}all${S}peer/d" \
                        -e "/^local${S}all${S}all${S}trust/d" \
                        -e "/^local${S}replication${S}all${S}trust/d" \
                        -e "/^host${S}all${S}all${S}.*scram-sha-256/d" \
                        "$HBA_FILE")
    echo "$CUSTOM_CONFIG" > "$CUSTOM_HBA_FILE"
fi

NEW_CONFIG="# This file is automatically generated by 01-pg_hba.sh.
# DO NOT MODIFY THIS FILE DIRECTLY!
# Your changes will be overwritten.
# To add custom rules, use pg_hba_custom.conf

include_if_exists pg_hba_custom.conf

local all all trust
local replication all trust
host all all 127.0.0.1/8 scram-sha-256
host all all ::1/128 scram-sha-256
$EXTERNAL_RULES"

for host in $INTERNAL_ACCESS; do
    NEW_CONFIG="$NEW_CONFIG
host all all $host scram-sha-256"
done

NEW_CONFIG="$NEW_CONFIG
hostssl reportdb all all scram-sha-256"

# Allow injection of extra HBA rules via environment variable for CI/CD
if [ -n "$POSTGRES_EXTRA_HBA_RULES" ]; then
   NEW_CONFIG="$NEW_CONFIG
$POSTGRES_EXTRA_HBA_RULES"
fi

if [[ "$(< "$HBA_FILE")" != "$NEW_CONFIG" ]]; then
    echo "$NEW_CONFIG" > "$HBA_FILE"
    PG_HBA_CHANGED=1
fi

# restart database to pickup new pg_hba changes
if [ -n "$PG_HBA_CHANGED" ]; then
    pg_ctl -D "$PGDATA" reload
fi
