/*
 * Copyright (c) 2025 SUSE LLC
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 */
package com.redhat.rhn.testing;

import static com.suse.manager.webui.services.SaltConstants.SALT_CONFIG_STATES_DIR;
import static com.suse.manager.webui.services.SaltConstants.SCRIPTS_DIR;
import static com.suse.manager.webui.services.SaltConstants.SUMA_STATE_FILES_ROOT_PATH;

import com.redhat.rhn.GlobalInstanceHolder;

import com.suse.manager.webui.services.ConfigChannelSaltManager;
import com.suse.manager.webui.services.SaltStateGeneratorService;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Comparator;
import java.util.stream.Stream;

/**
 * Utils for test case involving salt files
 */
public interface SaltTestCaseUtils {

    /**
     * Configure the classes working on salt files to write to a temporary directory and to not attempt
     * unauthorized operations during a unit test execution.
     * @return the path where the salt root is created
     * @throws IOException if salt root creation fails
     */
    default Path setupSaltConfigurationForTests() throws IOException {
        Path saltRoot = Files.createTempDirectory("salt");

        SaltStateGeneratorService.INSTANCE.setSkipSetOwner(true);
        SaltStateGeneratorService.INSTANCE.setSuseManagerStatesFilesRoot(saltRoot.toAbsolutePath());
        Files.createDirectory(saltRoot.resolve(SALT_CONFIG_STATES_DIR));
        ConfigChannelSaltManager.getInstance().setBaseDirPath(saltRoot.toAbsolutePath().toString());
        GlobalInstanceHolder.SALT_UTILS.setScriptsDir(saltRoot.resolve(SCRIPTS_DIR));

        return saltRoot;
    }

    /**
     * Restore the default configuration on all the classes modified by {@link #setupSaltConfigurationForTests()} and
     * removes all the files created during the test execution.
     * @param saltRoot the temporary salt root path, as generated by {@link #setupSaltConfigurationForTests()}
     * @throws IOException if clean up fails
     */
    default void cleanupSaltConfiguration(Path saltRoot) throws IOException {

        // Restore default configuration
        SaltStateGeneratorService.INSTANCE.setSkipSetOwner(false);
        SaltStateGeneratorService.INSTANCE.setSuseManagerStatesFilesRoot(Paths.get(SUMA_STATE_FILES_ROOT_PATH));
        ConfigChannelSaltManager.getInstance().setBaseDirPath(SUMA_STATE_FILES_ROOT_PATH);
        GlobalInstanceHolder.SALT_UTILS.setScriptsDir(Paths.get(SUMA_STATE_FILES_ROOT_PATH, SCRIPTS_DIR));

        if (saltRoot == null || !Files.isDirectory(saltRoot) || !Files.isWritable(saltRoot)) {
            return;
        }
        // Remove any created files
        try (Stream<Path> fileStream = Files.walk(saltRoot)) {
            fileStream.sorted(Comparator.reverseOrder())
                .map(Path::toFile)
                .forEach(File::delete);
        }
    }
}
