.TH susemanagerclient-plugin "8" "04 Apr 2013" "susemanager-plugin" "Support Utilities Manual"
.SH NAME
susemanagerclient-plugin \- SUSE Manager Client Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include
SUSE Manager Client information. Supportconfig saves the plugin output as plugin-susemanagerclient.txt.

.SH FILES
.I /usr/lib/supportconfig/plugins/susemanagerclient
.RS
The SUSE Manager Client plugin
.RE
.SH AUTHOR
Michael Calmer <Michael.Calmer@suse.com>
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
