#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SUSE Manager Client
# Description: Gathers important troubleshooting information
#              about a SUSE Manager Client
# License:     GPLv2
# Author:      Michael Calmer <mc@suse.de>
# Modified:    2024 February 03
#############################################################

SVER=5.0.0
RCFILE="/usr/lib/supportconfig/resources/supportconfig.rc"
OF='plugin-susemanager-client.txt'

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

log_write $OF
log_entry $OF note "Supportconfig Plugin for SUSE Manager Client, v${SVER}"
addHeaderFile $OF


#############################################################
RPMLIST="
spacewalk-client-tools
spacewalk-check
spacewalk-client-setup
rhnlib
osad
zypp-plugin-spacewalk
salt-minion
salt
podman
"

for THISRPM in $RPMLIST; do
    rpm_verify $OF $THISRPM
done

log_cmd $OF "/bin/ls -l --time-style=long-iso /usr/local/lib"
log_cmd $OF "/bin/ls -l --time-style=long-iso /usr/local/lib64"
log_cmd $OF "/bin/ls -l --time-style=long-iso /etc/ssl/certs/"

log_entry $OF note "SUSE Manager Client Config Files"

conf_files $OF \
    /etc/sysconfig/rhn/up2date \
    /etc/sysconfig/rhn/osad.conf \
    /etc/sysconfig/rhn/rhncfg-client.conf \
    /etc/sysconfig/rhn/rhncfg-manager.conf \
    /etc/sysconfig/rhn/image.cfg \
    /etc/sysconfig/rhn/rhnpushrc \
    /etc/sysconfig/rhn/systemid \
    /etc/salt/minion \
    /etc/salt/minion.d/susemanager.conf \
    /etc/salt/minion.d/_schedule.conf \
    /etc/uyuni/proxy/config.yaml


log_entry $OF note "SUSE Manager Client Log Files"

log_files $OF 1000 /var/log/salt/minion

log_cmd $OF "zypper --no-refresh ls"
log_cmd $OF "zypper --no-refresh lr -u"
log_cmd $OF "salt-minion --versions-report"

log_cmd $OF "cp /var/log/zypper.log $LOG"

log_entry $OF note "Crypto Policy"

if [ -f /etc/crypto-policies/config ]; then
        log_cmd $OF "cat /etc/crypto-policies/config"
elif [ $(cat /proc/sys/crypto/fips_enabled) -ne 0 ]; then
        log_write $OF "FIPS"
else
        log_cmd $OF "grep -v '#' /usr/share/crypto-policies/default-config"
fi

log_entry $OF note "Cloud / PAYG"
log_cmd $OF "test -e /usr/bin/instance-flavor-check && /usr/bin/instance-flavor-check"
rpm_verify $OF "python-instance-billing-flavor-check"


