#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SUSE Manager Client
# Description: Gathers important troubleshooting information
#              about a SUSE Manager Client
# License:     GPLv2
# Author:      Michael Calmer <mc@suse.de>
# Modified:    2013 October 10
#############################################################

SVER=1.0.0
RCFILE="/usr/lib/supportconfig/resources/scplugin.rc"
LOG_LINES=500  # 0 means include the entire file

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

validate_rpm_if_installed() {
        THISRPM=$1
        echo "#==[ Validating RPM ]=================================#"
        if rpm -q $THISRPM >/dev/null 2>&1; then
                echo "# rpm -V $THISRPM"

                if rpm -V $THISRPM; then
                        echo "Status: Passed"
                else
                        echo "Status: WARNING"
                fi
        else
                echo "package $THISRPM is not installed"
                echo "Status: Skipped"
        fi
        echo
}

#############################################################
section_header "Supportconfig Plugin for SUSE Manager Client, v${SVER}"
RPMLIST="
spacewalk-client-tools
spacewalk-check
spacewalk-client-setup
spacewalksd
rhnlib
osad
rhncfg
rhncfg-actions
rhncfg-client
rhncfg-management
rhn-custom-info
rhnmd
rhnpush
rhn-virtualization-common
rhn-virtualization-host
spacewalk-koan
spacewalk-backend-libs
spacewalk-remote-utils
spacewalk-oscap
suseRegisterInfo
zypp-plugin-spacewalk
python-dmidecode
koan
python-jabberpy
openscap
openscap-utils
libopenscap1
openscap-content
"

for THISRPM in $RPMLIST; do
        validate_rpm_if_installed $THISRPM
done

find_and_plog_files () {
        [ -d "$1" ] || return 0
        FILES=$(find "$@" ! -name \*.gz ! -name \*.bz2)
        if [ -n "$FILES" ]; then
                plog_files $LOG_LINES $FILES
        fi
}

section_header "SUSE Manager Client Config Files"

pconf_files \
    /etc/sysconfig/rhn/up2date \
    /etc/sysconfig/rhn/osad.conf \
    /etc/sysconfig/rhn/rhncfg-client.conf \
    /etc/sysconfig/rhn/rhnsd

section_header "SUSE Manager Client Capabilities"

find /etc/sysconfig/rhn/clientCaps.d/

section_header "SUSE Manager Client allowed Actions"

find /etc/sysconfig/rhn/allowed-actions/

section_header "SUSE Manager Proxy Log Files"

find_and_plog_files /var/log/up2date -type f
find_and_plog_files /var/log/osad -type f

