# Access Control List (ACL) configuration

# --- Anonymous Clients ---
# These rules apply to any client connecting without a username (like our Java publisher).

# Allow read access to all Uyuni event topics (uyuni/<fqdn>/<category>/<action>)
topic read uyuni/#

# Allow write access to all Uyuni event topics (uyuni/<fqdn>/<category>/<action>)
topic write uyuni/#
