# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the apacheServer.py for Spacewalk Proxy Server.
#

TOP	= ..
SUBDIR	= proxy/broker
FILES	= __init__ rhnRepository rhnBroker
include $(TOP)/Makefile.defs
