# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the xmlrpc module
#

TOP	= ../../..
SUBDIR	= upload_server/handlers/package_push

FILES	= __init__ package_push

include $(TOP)/Makefile.defs

