//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:02:18 PM CET 
//


package com.suse.oval.ovaltypes;

import com.suse.ovaltypes.linux.DpkginfoObject;
import com.suse.ovaltypes.linux.RpminfoObject;

import javax.xml.bind.annotation.*;
import java.math.BigInteger;


/**
 * The required id attribute uniquely identifies each object, and must conform to the format specified by the ObjectIdPattern simple type.
 * The required version attribute holds the current version of the object element. Versions are integers, starting at 1
 * and incrementing every time an object is modified. The optional comment attribute provides a short description of the object.
 * <p>
 * The optional deprecated attribute signifies that an id is no longer to be used or referenced but the information has been kept
 * around for historic purposes.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ObjectType", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5")
public class ObjectType {

    @XmlAttribute(name = "id", required = true)
    protected String id;
    @XmlAttribute(name = "version", required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger version;
    @XmlAttribute(name = "comment")
    protected String comment;
    @XmlAttribute(name = "deprecated")
    protected Boolean deprecated;


    // These attributes are not specified for the base object type as per the schema; nevertheless, they has been included
    // since both dpkg and rpm objects have them.

    @XmlElement(namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5#linux")
    protected String name;


    /**
     * Gets the value of the id property.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the version property.
     */
    public BigInteger getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     */
    public void setVersion(BigInteger value) {
        this.version = value;
    }

    /**
     * Gets the value of the comment property.
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the deprecated property.
     */
    public boolean isDeprecated() {
        if (deprecated == null) {
            return false;
        } else {
            return deprecated;
        }
    }

    /**
     * Sets the value of the deprecated property.
     */
    public void setDeprecated(Boolean value) {
        this.deprecated = value;
    }

    /**
     * Returns the package name.
     */
    public String getPackageName() {
        return name;
    }

    public void setPackageName(String name) {
        this.name = name;
    }

    public boolean isDpkg() {
        return this instanceof DpkginfoObject;
    }

    public boolean isRpm() {
        return this instanceof RpminfoObject;
    }
}
