/*
 * Copyright (c) 2023 SUSE LLC
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 *
 * Red Hat trademarks are not licensed under GPLv2. No permission is
 * granted to use or replicate Red Hat trademarks that are incorporated
 * in this software or its documentation.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:02:18 PM CET 
//


package com.suse.oval.ovaltypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.util.Optional;


/**
 * The required source attribute specifies where the reference is coming from. In other words, it identifies
 * the reference repository being used. The required ref_id attribute is the external id of the reference.
 * <p>
 * The optional ref_url attribute is the URL to the reference.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReferenceType", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5")
public class ReferenceType {

    @XmlAttribute(name = "source", required = true)
    protected String source;
    @XmlAttribute(name = "ref_id", required = true)
    protected String refId;
    @XmlAttribute(name = "ref_url")
    @XmlSchemaType(name = "anyURI")
    protected String refUrl;

    /**
     * Gets the value of the source property.
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the refId property.
     */
    public String getRefId() {
        return refId;
    }

    /**
     * Sets the value of the refId property.
     */
    public void setRefId(String value) {
        this.refId = value;
    }

    /**
     * Gets the value of the refUrl property.
     */
    public Optional<String> getRefUrl() {
        return Optional.ofNullable(refUrl);
    }

    /**
     * Sets the value of the refUrl property.
     */
    public void setRefUrl(String value) {
        this.refUrl = value;
    }

}
