//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.01 at 01:02:18 PM CET 
//


package com.suse.oval.ovaltypes;

import com.suse.ovaltypes.linux.DpkginfoState;
import com.suse.ovaltypes.linux.RpminfoState;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * The StatesType is a container for one or more state child elements.
 * Each state provides details about specific characteristics that can be used during an evaluation of an object.
 * <p>
 * Please refer to the description of the state element for more information about an individual state.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StatesType", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5")
public class StatesType {

    @XmlElements({
            @XmlElement(name = "rpminfo_state", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5#linux", type = RpminfoState.class),
            @XmlElement(name = "dpkginfo_state", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5#linux", type = DpkginfoState.class),
            @XmlElement(name = "state", namespace = "http://oval.mitre.org/XMLSchema/oval-definitions-5", type = StateType.class)
    })
    protected List<StateType> states;

    /**
     * Gets the contained states.
     */
    public List<StateType> getStates() {
        if (states == null) {
            states = new ArrayList<>();
        }
        return this.states;
    }

}
