#!/usr/bin/python3

# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: MIT

# pylint: disable=invalid-name
"""
Main CLI app.
"""
import mgrlibmod.mlapp

if __name__ == "__main__":
    mgrlibmod.mlapp.main()
