#!/bin/bash

umount /dev/shm
mount tmpfs -t tmpfs -o defaults /dev/shm

echo "Setting up Oracle 12 database..."
insserv oracle
/etc/init.d/oracle start

export MANAGER_USER=susemanager
export MANAGER_PASS=susemanager
export DEFAULT_TABLESPACE=data_tbs

MYHOSTNAME="localhost"

echo "
LISTENER =
  (DESCRIPTION_LIST =
    (DESCRIPTION =
      (ADDRESS = (PROTOCOL = TCP)(HOST = $MYHOSTNAME)(PORT = 1521))
      (ADDRESS = (PROTOCOL = IPC)(KEY = EXTPROC1521))
    )
  )
" > /opt/apps/oracle/product/12.1.0/dbhome_1/network/admin/listener.ora

echo "Create database user for SUSE Manager..."
echo "select value from nls_database_parameters where parameter='NLS_CHARACTERSET';
shutdown immediate;
startup mount;
alter system enable restricted session;
alter system set job_queue_processes=0;
alter database open;
alter database character set internal_use utf8;
shutdown immediate;
startup;
select value from nls_database_parameters where parameter='NLS_CHARACTERSET';
alter system set job_queue_processes=1000;
alter profile DEFAULT limit PASSWORD_LIFE_TIME unlimited;
create smallfile tablespace $DEFAULT_TABLESPACE datafile '/opt/apps/oracle/oradata/susemanager/data_01.dbf' size 500M autoextend on blocksize 8192;
create user $MANAGER_USER identified by \"$MANAGER_PASS\" default tablespace $DEFAULT_TABLESPACE;
grant dba to $MANAGER_USER;
grant connect to $MANAGER_USER;
grant alter session to $MANAGER_USER;
grant create table to $MANAGER_USER;
grant create view to $MANAGER_USER;
grant create type to $MANAGER_USER;
grant create sequence to $MANAGER_USER;
grant create procedure to $MANAGER_USER;
grant create operator to $MANAGER_USER;
grant create synonym to $MANAGER_USER;
grant create trigger to $MANAGER_USER;
grant create role to $MANAGER_USER;
grant alter session to $MANAGER_USER;
alter system set processes = 400 scope=spfile;
alter system set deferred_segment_creation=FALSE;
alter system set nls_territory='AMERICA' scope=spfile;
BEGIN
dbms_sqltune.set_auto_tuning_task_parameter( 'ACCEPT_SQL_PROFILES', 'TRUE');
END;
/
quit
" > /tmp/dbsetup.sql

su -s /bin/bash - oracle -c "ORACLE_SID=susemanager sqlplus / as sysdba @/tmp/dbsetup.sql;"
/etc/init.d/oracle restart

/etc/init.d/oracle stop
