# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

CAfile = /usr/share/rhn/RHNS-CA-CERT
client = yes
connect = xmlrpc.rhn.redhat.com:443
foreground = yes
verify = 2
