#!/bin/bash -fue

# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: MIT

set -- $SSH_ORIGINAL_COMMAND
cmd="$1"
shift
case "$cmd" in
  '/usr/bin/scp'|'/usr/bin/ssh'|'cat') exec "$cmd" "$@" ;;
  *) echo "ERROR: command not allowed" ;;
esac