# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the apacheServer.py for Spacewalk Proxy SSL Redirect Server.
#

TOP	= ..
SUBDIR	= proxy/redirect
FILES	= __init__ rhnRedirect
include $(TOP)/Makefile.defs

