# Container used to test java code of SUSE Manager
#
# VERSION               0.1


FROM PARENT_CONTAINER
MAINTAINER Flavio Castelli "fcastelli@suse.com"

# Make sure the package repository is up to date
RUN zypper --non-interactive --gpg-auto-import-keys ref

# Install needed packages
RUN zypper in -y perl-DBD-Pg \
                 postgresql91-contrib \
                 postgresql91-pltcl \
                 postgresql91-server \
                 smdba

ADD setup-db-postgres.sh /root/setup-db-postgres.sh
RUN sh /root/setup-db-postgres.sh

# Create a tomcat user - this is required later by spacewalk-setup
RUN useradd tomcat

# spacewalk-setup requires the following binaries in this precise place (cheating with
# PATH does not help):
#
#   * /usr/sbin/spacewalk-service
#   * /usr/bin/rhn-config-schema.pl
#
# These binaries are alredy inside of the git checkout, we just need some
# symbolick links pointing to them. We do not have out git checkout mounted
# inside of the container at build time, hence we are going to cheat a little...

RUN mkdir -p /manager/spacewalk/admin/
RUN touch /manager/spacewalk/admin/{spacewalk-service,rhn-config-schema.pl,rhn-config-satellite.pl}
RUN ln -s /manager/spacewalk/admin/spacewalk-service /usr/sbin/
RUN ln -s /manager/spacewalk/admin/rhn-config-schema.pl /usr/bin/
RUN ln -s /manager/spacewalk/admin/rhn-config-satellite.pl /usr/bin/
RUN mkdir -p /manager/spacewalk/setup/bin/
RUN ln -s /manager/spacewalk/setup/bin/spacewalk-make-mount-points /usr/bin/
RUN mkdir -p /var/lib/rhn/rhn-satellite-prep/etc/rhn
RUN ln -s /etc/rhn/rhn.conf /var/lib/rhn/rhn-satellite-prep/etc/rhn/
RUN rm -rf /manager

# The symlinks are broken right now, but they will work fine when we mount our
# git checkout on /manager

# Change the number of maximum connections allowed by PostgreSQL.
# This is by default 100, a value which is way too high compared to the actual
# needs of the test suites. A high value causes more memory to be requested by
# PostgreSQL on startup, leading to memory issues when two pgsql containers are
# are executed at the same time.
RUN sed -i 's/^max_connections =.*$/max_connections = 20/g' /var/lib/pgsql/data/postgresql.conf

