# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for installation of the httpd configuration files
#

# what is the backend top dir
TOP	= ..

APACHECONFDIR	= /etc/httpd/conf.d

INSTALL_FILES	= $(wildcard *.conf)
INSTALL_DEST	= $(APACHECONFDIR)

include $(TOP)/Makefile.defs
