# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the import code
#

TOP	= ../..

SUBDIR	= server/repomd

SPACEWALK_FILES	= __init__ mapper domain repository view

include $(TOP)/Makefile.defs
