#!/usr/bin/bash

# SPDX-FileCopyrightText: 2024 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

# This script is called by push-packages-to-obs
# To use it add the following to the tito.props of the package:
#
# [buildconfig]
# builder = custom.ChartBuilder

OSCAPI=$1
GIT_DIR=$2
PKG_NAME=$3

SRPM_PKG_DIR=$(dirname "$0")


# check which endpoint we are using to match the product
if [ "${OSCAPI}" == "https://api.suse.de" ]; then
  PRODUCT_VERSION="$(sed -n 's/.*web.version\s*=\s*\(.*\)$/\1/p' ${GIT_DIR}/web/conf/rhn_web.conf)"
else
  # Uyuni settings
  PRODUCT_VERSION="$(sed -n 's/.*web.version.uyuni\s*=\s*\(.*\)$/\1/p' ${GIT_DIR}/web/conf/rhn_web.conf)"
fi
# to lowercase with ",," and replace spaces " " with "-"
PRODUCT_VERSION=$(echo ${PRODUCT_VERSION,,} | sed -r 's/ /-/g')


if [ -f "${SRPM_PKG_DIR}/Chart.yaml" ]; then
    NAME="${PKG_NAME}"
    if [ "${OSCAPI}" == "https://api.suse.de" ]; then
        # SUSE Manager settings
        VERSION=$(echo ${PRODUCT_VERSION} | sed 's/^\([0-9]\+\.[0-9]\+\).*$/\1/')
        sed "/^#\!BuildTag:/s/uyuni/suse\/manager\/${VERSION}/g" -i ${SRPM_PKG_DIR}/Chart.yaml
        sed "s/^home: .*$/home: https:\/\/www.suse.com\/products\/suse-manager\//" -i ${SRPM_PKG_DIR}/Chart.yaml
        CHART_TAR=$(ls ${SRPM_PKG_DIR}/*.tar)
        mkdir ${SRPM_PKG_DIR}/tar
        tar xf $CHART_TAR -C ${SRPM_PKG_DIR}/tar
        sed "s/^repository: .\+$/repository: registry.suse.com\/suse\/manager\/${VERSION}/" -i ${SRPM_PKG_DIR}/tar/values.yaml
        tar cf $CHART_TAR -C ${SRPM_PKG_DIR}/tar .
        rm -rf ${SRPM_PKG_DIR}/tar
        NAME="suse\/manager\/${VERSION}\/${NAME}"
    else
        NAME="uyuni\/${NAME}"
    fi

    sed "/^version:.\+$/aappVersion: \"${PRODUCT_VERSION}\"" -i ${SRPM_PKG_DIR}/Chart.yaml
    # Remove leading zero from Uyuni release and add potentially missing micro part
    SEMANTIC_VERSION=$(echo ${PRODUCT_VERSION} | sed 's/\([0-9]\+\)\.0\?\([1-9][0-9]*\)\(\.\([0-9]\+\)\)\?\( .\+\)\?/\1.\2.\4\5/' | sed 's/\.$/.0/')
    # Also include the semantic version since helm chart wants it for OCI repos (those generated by OBS)
    sed "/^#\!BuildTag:/ s/$/ ${NAME}:${SEMANTIC_VERSION} ${NAME}:${PRODUCT_VERSION} ${NAME}:${PRODUCT_VERSION}.%RELEASE%/" -i ${SRPM_PKG_DIR}/Chart.yaml

    rm ${SRPM_PKG_DIR}/${PKG_NAME}.spec
fi

