.DEFAULT_GOAL  :=  __unspecified

define update_pip_env
	rpm -e python3-pylint &>/dev/null
	pip3 install --upgrade pip
	pip3 uninstall -y pylint
	pip3 install pylint==2.3.1
	mkdir -p reports
endef


define install_pytest
	pip3 install pytest==4.4.0
endef


define install_by_setup
	cd $1
	rm -rf dist
	python3 setup.py sdist
	pip3 install dist/*
	rm -rf dist
endef

__unspecified ::
	@echo "Specify some target, please"
	@exit 1

__pytest_refresh ::
	$(call install_by_setup, '.')
