.DEFAULT_GOAL  :=  __unspecified

define update_pip_env
	rpm -e python3-pylint &>/dev/null
	pip3 install --upgrade pip
	pip3 uninstall -y pylint
	pip3 install pylint==2.3.1
	mkdir -p reports
endef


__unspecified ::
	@echo "Specify some target, please"
	@exit 1
