# On Kubernetes the tmp mounts (and others) cannot be remounted.
# Disable the protections in the container for services to start
[Service]
ProtectSystem=false
PrivateTmp=no
ProtectHome=false
PrivateDevices=false
ProtectHostname=false
ProtectClock=false
ProtectKernelTunables=false
ProtectKernelModules=false
ProtectKernelLogs=false
ProtectControlGroups=false
RestrictRealtime=false
