[[s3-sm-errata-details]]
= Patch Details

If you click the advisory of a patch in the [guimenu]``Relevant`` or [guimenu]``All`` pages, its [guimenu]``Patch Details`` page appears.
This page is further divided into the following tabs:



[[s4-sm-errata-details-details]]
== Details

This subtab displays the patch report issued by {suse}.
It provides a synopsis of the patch first (with the severity as a textual prefix in case of security updates, such as "`critical`", "`important`", "`moderate`", or "`low`"), issue date, and any update dates.
This is followed by a description of the patch and the steps required to resolve the issue.

Below the [guimenu]``Affected Channels`` label, all channels that contain the affected package are listed.
Clicking a channel name displays the [guimenu]``Packages`` subtab of the [guimenu]``Channel Details`` page for that channel.
Refer to xref:reference:patches/patch-details.adoc[Patch Details] for more information.

Security updates list the specific vulnerability as tracked by link:http://cve.mitre.org[].
This information is listed below the [guimenu]``CVEs`` label.

OVAL is an open vulnerability and assessment language promoted by Mitre, link:http://oval.mitre.org[].
Clicking the link below the [guimenu]``Oval`` label downloads this information to your system.

More useful are the {suse} Update Advisories at link:https://www.suse.com/support/update/[].



[[s4-sm-errata-details-packages]]
== Packages

This page provides links to each of the updated RPMs by channel.
Clicking the name of a package displays its [guimenu]``Package Details`` page.



[[s4-sm-errata-details-systems]]
== Affected Systems

This page lists systems affected by the patches.
You can apply updates here.
(See xref:reference:patches/applying-patches.adoc[Applying Patches].) Clicking the name of a system takes you to its [guimenu]``System Details`` page.
Refer to xref:reference:systems/system-details.adoc[System Details] for more information.

To determine whether an update has been scheduled, refer to the [guimenu]``Status`` column in the affected systems table.
Possible values are: N/A, Pending, Picked Up, Completed, and Failed.
This column identifies only the last action related to a patch.
For example, if an action fails and you reschedule it, this column shows the status of the patch as pending with no mention of the previous failure.
Clicking a status other than [guimenu]``N/A`` takes you to the [guimenu]``Action Details`` page.
This column corresponds to one on the [guimenu]``Patch`` tab of the [guimenu]``System Details`` page.
