[[retail-migration-slepostosuma]]
= Migrate {slepos} 11 to {smr}


This section describes migrating from an existing {slepos} 11 installation to a new {susemgr} installation.
You can perform this migration all at once by creating a data dump in a single file, and then moving it to the new server.

Alternatively, you can perform the migration in stages by creating a data dump for each branch, and moving them to the new server one by one.
Importing and deploying the converted data can also be done in one or multiple steps, depending on your environment.



[[retail_migr.sect.slepostosuma.s1.complete]]
== Migration with Complete Data Dump

In this procedure, you create a single data dump in an XML file, convert it to YAML, and migrate it to the new infrastructure all at once.

. Install a {smr} server {productnumber}.
For more information, see xref:retail:retail-install-unified.adoc[].
. On the SLEPOS Admin server export all the data stored in LDAP to an XML file.
Run this command as an administrator:
+
----
posAdmin --export --type xml --file dumpfile.xml
----
+
The resulting [literal]``dumpfile.xml`` file will contain global information, with parts about images, hardware and its partitioning, and the description of the branch servers with networking data, services, and attached terminals.

. Move the XML file to the newly created {susemgr} server, and convert it to YAML:
+
----
retail_migration dumpfile.xml retail.yml
----

. Review the generated YAML file ([literal]``retail.yml``) and adjust it as necessary.
Consider ``HWTYPE`` group naming and image name and version changes in the partitioning data.  Group names must not exceed the 56 character limit.
You can shorten the names as needed, and the image names must match the images in {susemgr}.
The [option]``--save-mapping`` option can help you with this task.
+
Also check whether there are duplicate MAC addresses of the terminals in the generated YAML file.
Choose which entry you want to keep.
If there are duplicate MAC addresses, importing the YAML file will fail.
+
[NOTE]
====
{slepos} images will not be migrated. You must rebuild the images using the OS image building functionality.
For more information about building images, see xref:administration:image-management.adoc[].
====

. Import the complete data (YAML) with:
+
----
retail_yaml --from-yaml retail.yml
----
+
You can see statistical data while importing.  Then check the results in the {webui}. In menu:Main Menu[Systems > Systems > All], find empty profiles, and in menu:Main Menu[Systems > Groups], the groups for the hardware configuration, the branches, servers, and terminals.


To finalize the branch server migration, you must install the branch server machines as Salt clients and bootstrap them as proxies.
For more information about proxy installation, see xref:retail:retail-install.adoc[].
For more information about using an activation key to assign the required channels, see xref:retail:retail-install-setup.adoc[].
After onboarded to {susemgr}, the branch servers machines are connected with the empty profiles (by FQDN), and so they will get the Retail configuration.

After all the branches are migrated, shutdown and remove the old SLEPOS Admin Server.



[[retail_migr.sect.slepostosuma.s1.bbb]]
== Migration with Branch by Branch Data Dump

In this procedure, you migrate the SLEPOS infrastructure and the branches one by one, first exporting and then importing.

. Install a {smr} server {productnumber}
For more information, see xref:retail:retail-install-unified.adoc[].

. On every branch server:
+
----
posAdmin --export --type xml --file dumpfile.xml
----
+
These dumps will contain only the LDAP data of the branch, and any global data.

. Similarily, you can export the LDAP data of every branch if you run the command on the Admin server with the branch credentials explicitly specified:
+
----
posAdmin --export --type xml --file dumpfile.xml --user $branch_dn \
    --password $password
----
+
For background information about SLEPOS branch server configuration, see https://documentation.suse.com/sle-pos/11-SP3/html/SLEPOS-guide/cha.slepos_branchserv.html.

. Review the generated YAML file ([literal]``retail.yml``) and adjust it as necessary.
Consider ``HWTYPE`` group naming and image name and version changes in the partitioning data.
You can shorten the names as needed, and the image names must match the images in {susemgr}.
The [option]``--save-mapping`` option can help you with this task.
+
Check whether there are duplicate MAC addresses of the terminals in the generated YAML file.
Choose which entry you want to keep.
As long as there are duplicate MAC addresses, {susemgr} will refuse importing the YAML file.
+
[NOTE]
====
{slepos} images will not be migrated. You must rebuild the images using the OS image building functionality.
For more information about building images, see xref:administration:image-management.adoc[].
====

The data can be imported branch by branch.
For each branch perform the following steps:

// . Replace each old SLEPOS branch server with a {smr} branch server (see https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.install.html[Install Branch Server]) and connect it to the {smr} server (the same procedure as for https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.admin.html#retail.sect.admin.branch_mass_config[Branch Server Mass Configuration]).
// +
// Use the empty profiles together with activation keys to onboard all the systems of your infrastructure.
// Use an activation key to assign the channels listed in https://www.suse.com/documentation/suse-manager-for-retail-3-2/retail-getting-started/retail.chap.install.html[Configuring Server].

. Run the import command for one branch after the other:
+
----
retail_yaml --from-yaml retail.yml --branch <branch_name>
----
+
Repeat the command for every branch.

. To finalize each branch server migration, you must install the branch server machine as a Salt-based client and bootstrap it as a proxy.
For more information about proxy installation, see xref:retail-install.adoc#retail.sect.install.branch[Installing and Registering].
For more information about using an activation key to assign the required channels, see xref:retail-install.adoc#retail.sect.install.install.config[Configuring Server].
After onboarded to {smr}, the branch server machine is connected with the empty profile (by FQDN), and so it will get the Retail configuration.

. Apply Highstate on the branch server; this will happen automatically if [guimenu]``Configuration File Deployment`` is enabled.

. Boot the terminals of the branch.

After all the branches are migrated, shut down and remove the old SLEPOS Admin Server.



[[retail_migr.sect.slepostosuma.s1.x2y]]
== Converting XML to YAML

When you perform a migration using one of the methods in this chapter, one of the steps takes the XML data dump file from {slepos}, and converts it to a YAML file for {smr}.
The tool that performs this conversion has additional features, which are outlined in this section.

To validate the XML file before conversion, and print any errors:

----
retail_migration dumpfile.xml
----


To write a mapping file called [path]``map.yml``:

----
retail_migration dumpfile.xml  --save-mapping map.yml
----

The mapping file contains two dictionaries:
. [systemitem]``images``, which maps old {slepos} images to new images built in {susemgr}.
. [systemitem]``groups``, which maps legacy {slepos} [systemitem]``scCashRegister`` objects to {susemgr} [systemitem]``HWTYPE`` groups.
Group names must not exceed the 56 character limit.

The mapping file should be edited as required for your environment.


To perform a conversion using a mapping file:

----
retail_migration dumpfile.xml  retail.yml --mapping map.yml
----

If you are performing a branch-by-branch migration, the resulting [path]``retail.yml`` file will contain a new version of {slepos} LDAP data.
If you want to preserve any global changes in your {smr} settings, remove the [systemitem]``global`` hardware types from the resulting [path]``retail.yml`` file before importing it.
Alternatively, you can import [path]``retail.yml`` using this command to import only the new systems and groups defined in the file, and leave any existing configuration settings untouched:

----
retail_yaml --only-new
----
