[[retail-migration-intro]]
= Retail Migration


////
// 2019-08-20, ke:
// I think we no longer need this intro.
// The chapter now is part of the Retail Guide
[[retail_migr.sect.intro.what]]
== What is {smr}?

{smr} is an open source infrastructure management solution, optimized and tailored specifically for the retail industry.
It uses the same technology as {susemgr}, but is customized to address the needs of retail organizations.

{smr} is designed for use in retail situations where customers can use point-of-service terminals to purchase or exchange goods, take part in promotions, or collect loyalty points.
In addition to retail installations, it can also be used for novel purposes, such as maintaining student computers in an educational environment, or self-service kiosks in banks or hospitals.

{smr} is intended for use in installations that include servers, workstations, point-of-service terminals, and other devices.
It allows administrators to install, configure, and update the software on their servers, and manage the deployment and provisioning of point-of-service machines.
////

////
[[retail.about.this.book]]
== About this book
////

This section provides instructions for migrating {slepos} 11, {smr} 3.1, or {smr} 3.2 to {smr} 4.0.

////
It should be read in conjunction with the {smr} documentation suite, available from https://www.suse.com/documentation/suse-manager-for-retail/.
////
