/*
 * Copyright (c) 2024--2025 SUSE LLC
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 */
package com.suse.manager.model.hub;

import com.redhat.rhn.domain.BaseDomainHelper;
import com.redhat.rhn.domain.credentials.SCCCredentials;

import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

@Entity
@Table(name = "suseISSHub")
public class IssHub extends BaseDomainHelper implements IssServer {
    private Long id;
    private String fqdn;
    private String rootCa;
    private String gpgKey;
    private SCCCredentials mirrorCredentials;

    protected IssHub() {
        // Default empty Constructor for Hibernate
    }

    @Transient
    public IssRole getRole() {
        return IssRole.HUB;
    }

    /**
     * Constructor
     * @param fqdnIn the FQDN of the Hub Server
     */
    public IssHub(String fqdnIn) {
        this (fqdnIn, null);
    }

    /**
     * Constructor
     * @param fqdnIn the FQDN of the Hub Server
     * @param rootCaIn the root CA used by the Hub Server
     */
    public IssHub(String fqdnIn, String rootCaIn) {
        fqdn = fqdnIn;
        rootCa = rootCaIn;
        mirrorCredentials = null;
    }

    /**
     * @return return the ID
     */
    @Id
    @Column(name = "id")
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Override
    public Long getId() {
        return id;
    }

    /**
     * Get the FQDN of the Hub Server
     * @return return the FQDN of the Hub Server
     */
    @Column(name = "fqdn", unique = true)
    @Override
    public String getFqdn() {
        return fqdn;
    }

    /**
     * Get the configured Root CA
     * @return return the root ca
     */
    @Column(name = "root_ca")
    @Override
    public String getRootCa() {
        return rootCa;
    }

    /**
     * Get the configured GPG Key
     * @return return the gpg key
     */
    @Column(name = "gpg_key")
    public String getGpgKey() {
        return gpgKey;
    }

    /**
     * Get the mirror credentials.
     * @return the credentials
     */
    @OneToOne(targetEntity = SCCCredentials.class)
    @JoinColumn(name = "mirror_creds_id")
    public SCCCredentials getMirrorCredentials() {
        return mirrorCredentials;
    }

    /*
     * will be autogenerated
     */
    protected void setId(Long idIn) {
        id = idIn;
    }

    /**
     * @param fqdnIn the FQDN
     */
    @Override
    public void setFqdn(String fqdnIn) {
        fqdn = fqdnIn;
    }

    /**
     * @param rootCaIn the root ca
     */
    @Override
    public void setRootCa(String rootCaIn) {
        rootCa = rootCaIn;
    }

    /**
     * @param gpgKeyIn the gpg key
     */
    public void setGpgKey(String gpgKeyIn) {
        gpgKey = gpgKeyIn;
    }

    /**
     * @param mirrorCredentialsIn the mirror credentials
     */
    public void setMirrorCredentials(SCCCredentials mirrorCredentialsIn) {
        mirrorCredentials = mirrorCredentialsIn;
    }

    @Override
    public boolean equals(Object oIn) {
        if (this == oIn) {
            return true;
        }
        if (!(oIn instanceof IssHub issHub)) {
            return false;
        }
        return Objects.equals(getFqdn(), issHub.getFqdn()) &&
                Objects.equals(getRootCa(), issHub.getRootCa()) &&
                Objects.equals(getMirrorCredentials(), issHub.getMirrorCredentials());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getFqdn(), getRootCa(), getMirrorCredentials());
    }

    @Override
    public String toString() {
        return "IssHub{" +
                "id=" + id +
                ", fqdn='" + fqdn + '\'' +
                '}';
    }
}
