# Container used to test java code of SUSE Manager
#
# VERSION               0.1

FROM PARENT_CONTAINER
MAINTAINER Flavio Castelli "fcastelli@suse.com"

# Make sure the package repository is up to date
RUN zypper --non-interactive --gpg-auto-import-keys --no-gpg-checks ref 

# Install needed packages
RUN zypper in -y bc \
                 openssh \
                 oracle-instantclient11_2-sqlplus \
                 perl-DBD-ODBC \
                 perl-DBD-Oracle

# Create a tomcat user - this is required later by spacewalk-setup
RUN useradd tomcat

# spacewalk-setup requires the following binaries in this precise place (cheating with
# PATH does not help):
#
#   * /usr/sbin/spacewalk-service
#   * /usr/bin/rhn-config-schema.pl
#
# These binaries are alredy inside of the git checkout, we just need some
# symbolic links pointing to them. We do not have the git checkout mounted
# inside of the container at build time, hence we are going to cheat a little...

RUN mkdir -p /manager/spacewalk/admin/
RUN touch /manager/spacewalk/admin/{spacewalk-service,rhn-config-schema.pl,rhn-config-satellite.pl}
RUN ln -s /manager/spacewalk/admin/spacewalk-service /usr/sbin/
RUN ln -s /manager/spacewalk/admin/rhn-config-schema.pl /usr/bin/
RUN ln -s /manager/spacewalk/admin/rhn-config-satellite.pl /usr/bin/
RUN mkdir -p /manager/spacewalk/setup/bin/
RUN ln -s /manager/spacewalk/setup/bin/spacewalk-make-mount-points /usr/bin/
RUN mkdir -p /var/lib/rhn/rhn-satellite-prep/etc/rhn
RUN ln -s /etc/rhn/rhn.conf /var/lib/rhn/rhn-satellite-prep/etc/rhn/
RUN rm -rf /manager

# The symlinks are broken right now, but they will work fine when we mount our
# git checkout on /manager

ADD tnsnames.ora /etc/tnsnames.ora

ADD ssh /root/.ssh
RUN chown -R root:root /root/.ssh
RUN chmod 600 /root/.ssh/*
