[[spacecmd.functions.org]]
= org_

The following spacecmd functions are available for use with organizations.



== org_addtrust

Add a trust between two organizations

[source]
--
usage: org_addtrust YOUR_ORG ORG_TO_TRUST
--



== org_create

Create an organization.

[source]
--
usage: org_create [options]

options:
  -n ORG_NAME
  -u USERNAME
  -P PREFIX (Dr., Mr., Miss, Mrs., Ms.)
  -f FIRST_NAME
  -l LAST_NAME
  -e EMAIL
  -p PASSWORD
  --pam enable PAM authentication
--



== org_delete

Delete an organization.

[source]
--
usage: org_delete NAME
--



== org_details

Show the details of an organization.

[source]
--
usage: org_details NAME
--



== org_list

List all organizations.

[source]
--
usage: org_list
--



== org_listtrusts

List an organization's trusts.

[source]
--
org_listtrusts NAME
--



== org_listusers

List an organization's users.

[source]
--
org_listusers NAME
--



== org_removetrust

Remove a trust between two organizations.

[source]
--
usage: org_removetrust YOUR_ORG TRUSTED_ORG
--



== org_rename

Rename an organization.

[source]
--
usage: org_rename OLDNAME NEWNAME
--



== org_trustdetails

Show the details of an organizational trust.

[source]
--
usage: org_trustdetails TRUSTED_ORG
--
