# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

Alias /os-images /srv/www/os-images
Alias /tftp      /srv/tftpboot

<Directory "/srv/www/os-images">
    SetEnv VIRTUALENV
    Require all granted
</Directory>

<Directory "/srv/tftpboot">
    SetEnv VIRTUALENV
    Options FollowSymLinks
    AllowOverride None
    Require all granted
</Directory>
