Alias /pub/RHN-ORG-TRUSTED-SSL-CERT /etc/pki/trust/anchors/LOCAL-RHN-ORG-TRUSTED-SSL-CERT
Alias /pub /srv/www/htdocs/pub
<Directory "/srv/www/htdocs/pub">
    SetEnv VIRTUALENV
    Options Indexes SymLinksIfOwnerMatch
    Require all granted
    AllowOverride All
</Directory>

<Directory "/etc/pki/trust/anchors">
    Require all denied
    <Files "LOCAL-RHN-ORG-TRUSTED-SSL-CERT">
        Require all granted
    </Files>
</Directory>
