Alias /pub /srv/www/htdocs/pub
Alias /pub/RHN-ORG-TRUSTED-SSL-CERT /etc/pki/trust/anchors/LOCAL-RHN-ORG-TRUSTED-SSL-CERT
<Directory "/srv/www/htdocs/pub">
    SetEnv VIRTUALENV
    Options Indexes SymLinksIfOwnerMatch
    Require all granted
    AllowOverride All
</Directory>
