ALTER TABLE system
    ADD COLUMN IF NOT EXISTS machine VARCHAR(64),
    ADD COLUMN IF NOT EXISTS rack VARCHAR(64),
    ADD COLUMN IF NOT EXISTS room VARCHAR(32),
    ADD COLUMN IF NOT EXISTS building VARCHAR(128),
    ADD COLUMN IF NOT EXISTS address1 VARCHAR(128),
    ADD COLUMN IF NOT EXISTS address2 VARCHAR(128),
    ADD COLUMN IF NOT EXISTS city VARCHAR(128),
    ADD COLUMN IF NOT EXISTS state VARCHAR(60),
    ADD COLUMN IF NOT EXISTS country VARCHAR(2)
;
