pylint ::
	pylint -e --enable-msg-cat=imports src/ || pylint --errors-only --enable=imports --disable=W src/

unittest ::
	if test -x /usr/bin/unit2 ; then \
                unit2 discover -s src; \
        else \
                python -munittest discover -s src; \
        fi
