# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the app module
#

TOP	= ../../..
SUBDIR	= server/handlers/app

FILES	= __init__ packages

include $(TOP)/Makefile.defs

