# Container used to test python code of SUSE Manager
#
# VERSION               0.1

FROM PARENT_CONTAINER
MAINTAINER Flavio Castelli "fcastelli@suse.com"

# make sure the package repository is up to date
RUN zypper --non-interactive --gpg-auto-import-keys ref

RUN zypper in -y  cx_Oracle \
                  make \
                  pylint \
                  python \
                  python-base \
                  python-crypto \
                  python-curl \
                  python-debian \
                  python-devel \
                  python-dmidecode \
                  python-ethtool \
                  python-gobject2 \
                  python-gpgme \
                  python-gzipstream \
                  python-iniparse \
                  python-logilab-astng \
                  python-logilab-common \
                  python-mock \
                  python-newt \
                  python-nose \
                  python-openssl \
                  python-pam \
                  python-psycopg2 \
                  python-selinux \
                  python-setools \
                  python-unittest2 \
                  python-urlgrabber \
                  python-xml \
                  rpm-python \
                  yum

RUN mkdir -p /usr/share/rhn/

RUN mkdir -p /manager/backend/rhn-conf/
RUN ln -s /manager/backend/rhn-conf/ /usr/share/rhn/config-defaults
RUN rm -rf /manager/backend

ADD rhn.conf /etc/rhn/rhn.conf
