# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

version: '3.8'
services:
  uyuni-dev:
    build:
      context: .
      dockerfile: Dockerfile
  
  uyuni-server:
    build:
      context: .
      dockerfile: Dockerfile
