export const placeholderData = {
  channelSyncData: {
    peripheralOrgs: [{ orgId: 1, orgName: "SUSE Test" }],
    channels: [
      {
        channelId: 114,
        channelName: "SL-Micro-6.0-Pool for x86_64",
        channelLabel: "sl-micro-6.0-pool-x86_64",
        channelArch: "x86_64",
        channelOrg: null,
        parentChannelLabel: null,
        originalChannelLabel: null,
        children: [
          {
            channelId: 115,
            channelName: "ManagerTools-SL-Micro-6.0 for x86_64",
            channelLabel: "managertools-sl-micro-6.0-x86_64",
            channelArch: "x86_64",
            channelOrg: null,
            parentChannelLabel: "sl-micro-6.0-pool-x86_64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 116,
            channelName: "ManagerTools-Beta-SL-Micro-6.0 for x86_64",
            channelLabel: "managertools-beta-sl-micro-6.0-x86_64",
            channelArch: "x86_64",
            channelOrg: null,
            parentChannelLabel: "sl-micro-6.0-pool-x86_64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
        ],
        clones: [],
        synced: false,
      },
      {
        channelId: 102,
        channelName: "SUSE-MicroOS-5.0-Pool for aarch64",
        channelLabel: "suse-microos-5.0-pool-aarch64",
        channelArch: "AArch64",
        channelOrg: null,
        parentChannelLabel: null,
        originalChannelLabel: null,
        children: [
          {
            channelId: 103,
            channelName: "SUSE-MicroOS-5.0-Updates for aarch64",
            channelLabel: "suse-microos-5.0-updates-aarch64",
            channelArch: "AArch64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-aarch64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 104,
            channelName: "ManagerTools-SLE-Micro5-Pool for aarch64 5.0",
            channelLabel: "managertools-sle-micro5-pool-aarch64-5.0",
            channelArch: "AArch64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-aarch64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 105,
            channelName: "ManagerTools-SLE-Micro5-Updates for aarch64 5.0",
            channelLabel: "managertools-sle-micro5-updates-aarch64-5.0",
            channelArch: "AArch64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-aarch64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 106,
            channelName: "ManagerTools-Beta-SLE-Micro5-Pool for aarch64 5.0",
            channelLabel: "managertools-beta-sle-micro5-pool-aarch64-5.0",
            channelArch: "AArch64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-aarch64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 107,
            channelName: "ManagerTools-Beta-SLE-Micro5-Updates for aarch64 5.0",
            channelLabel: "managertools-beta-sle-micro5-updates-aarch64-5.0",
            channelArch: "AArch64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-aarch64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
        ],
        clones: [],
        synced: false,
      },
      {
        channelId: 108,
        channelName: "SUSE-MicroOS-5.0-Pool for x86_64",
        channelLabel: "suse-microos-5.0-pool-x86_64",
        channelArch: "x86_64",
        channelOrg: null,
        parentChannelLabel: null,
        originalChannelLabel: null,
        children: [
          {
            channelId: 109,
            channelName: "SUSE-MicroOS-5.0-Updates for x86_64",
            channelLabel: "suse-microos-5.0-updates-x86_64",
            channelArch: "x86_64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-x86_64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 110,
            channelName: "ManagerTools-SLE-Micro5-Pool for x86_64 5.0",
            channelLabel: "managertools-sle-micro5-pool-x86_64-5.0",
            channelArch: "x86_64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-x86_64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 111,
            channelName: "ManagerTools-SLE-Micro5-Updates for x86_64 5.0",
            channelLabel: "managertools-sle-micro5-updates-x86_64-5.0",
            channelArch: "x86_64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-x86_64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 112,
            channelName: "ManagerTools-Beta-SLE-Micro5-Updates for x86_64 5.0",
            channelLabel: "managertools-beta-sle-micro5-updates-x86_64-5.0",
            channelArch: "x86_64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-x86_64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
          {
            channelId: 113,
            channelName: "ManagerTools-Beta-SLE-Micro5-Pool for x86_64 5.0",
            channelLabel: "managertools-beta-sle-micro5-pool-x86_64-5.0",
            channelArch: "x86_64",
            channelOrg: null,
            parentChannelLabel: "suse-microos-5.0-pool-x86_64",
            originalChannelLabel: null,
            children: [],
            clones: [],
            synced: false,
          },
        ],
        clones: [],
        synced: false,
      },
      {
        channelId: 101,
        channelName: "testchannel",
        channelLabel: "testchannel",
        channelArch: "x86_64",
        channelOrg: { orgId: 1, orgName: "SUSE Test" },
        parentChannelLabel: null,
        originalChannelLabel: null,
        children: [],
        clones: [],
        synced: false,
      },
    ],
  },
};
