{{- $config := .Values.global.config | fromYaml }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-configmap
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
data:
  config.yaml: |
{{ .Values.global.config | indent 4 }}
{{- if not (hasKey $config "log_level") }}
    log_level: 1
{{- end }}

  squid_tuning: |
    # Add your Squid tuning configuration here
{{ .Values.squid.tuning | indent 4 }}
  ssh_tuning: |
    # Add your SSHd tuning configuration here
{{ .Values.ssh.tuning | indent 4 }}
  apache_tuning: |
    # Add your Apache tuning configuration here
{{ .Values.httpd.tuning | indent 4 }}
  salt_tuning: |
    # Add your Salt Broker tuning configuration here
{{- if .Values.salt.tuning }}
{{ .Values.salt.tuning | indent 4 }}
{{- else }}
    {}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: httpd
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
stringData:
  httpd.yaml: |
{{ .Values.global.httpd | indent 4 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ssh
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
stringData:
  ssh.yaml: |
{{ .Values.global.ssh | indent 4 }}
