apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
spec:
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
  type: ClusterIP
  ports:
    - name: http
      port: 80
    - name: https
      port: 443
---
apiVersion: v1
kind: Service
metadata:
  name: salt
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
{{- if or .Values.services.annotations .Values.services.salt.annotations }}
  annotations:
{{ toYaml ( mergeOverwrite (dict) (default (dict) .Values.services.annotations) (default (dict) .Values.services.salt.annotations) ) | indent 4 }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
  type: {{ .Values.services.salt.type | default .Values.services.type }}
  ports:
    - name: publish
      port: 4505
{{- if eq (default .Values.services.type .Values.services.salt.type) "NodePort" }}
      nodePort: {{ .Values.services.salt.ports.publish }}
{{- end }}
    - name: request
      port: 4506
{{- if eq (default .Values.services.type .Values.services.salt.type) "NodePort" }}
      nodePort: {{ .Values.services.salt.ports.request }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: ssh
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
{{- if or .Values.services.annotations .Values.services.ssh.annotations }}
  annotations:
{{ toYaml ( mergeOverwrite (dict) (default (dict) .Values.services.annotations) (default (dict) .Values.services.ssh.annotations) ) | indent 4 }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
  type: {{ .Values.services.ssh.type | default .Values.services.type }}
  ports:
    - name: ssh
      port: 8022
      targetPort: 22
{{- if eq (default .Values.services.type .Values.services.ssh.type) "NodePort" }}
      nodePort: {{ .Values.services.ssh.ports.ssh }}
{{- end }}
{{- if not .Values.tftp.hostNetwork }}
---
apiVersion: v1
kind: Service
metadata:
  name: tftp
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
{{- if or .Values.services.annotations .Values.services.tftp.annotations }}
  annotations:
{{ toYaml ( mergeOverwrite (dict) (default (dict) .Values.services.annotations) (default (dict) .Values.services.tftp.annotations) ) | indent 4 }}
{{- end }}
spec:
  selector:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
  # ClusterIP or NodePort wouldn't work for TFTP if not using the host network
  type: LoadBalancer
  # Ensures all packets from a single client go to the same pod
  sessionAffinity: ClientIP
  # Preserves the client's source IP and avoids extra hops between nodes
  externalTrafficPolicy: Local
  ports:
    - name: tftp
      port: 69
      protocol: UDP
{{- end }}
