{{- if and (not .Values.gateway.enable) (eq ((.Values.ingress).type) "traefik") }}
  {{- if ne (default .Values.services.type .Values.services.ssh.type) "NodePort" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ssh-router
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
  {{- if .Values.ingress.class }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints.ssh | default "ssh" }}
  routes:
    - match: HostSNI(`*`)
      services:
      - name: ssh
        port: 8022
---
  {{- end }}
  {{- if ne (default .Values.services.type .Values.services.salt.type) "NodePort" }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: salt-publish-router
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
  {{- if .Values.ingress.class }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints.saltPublish | default "salt-publish" }}
  routes:
    - match: HostSNI(`*`)
      services:
      - name: salt
        port: 4505
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: salt-request-router
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/component: proxy
    app.kubernetes.io/part-of: uyuni
  {{- if .Values.ingress.class }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class | quote }}
  {{- end }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoints.saltRequest | default "salt-request" }}
  routes:
    - match: HostSNI(`*`)
      services:
      - name: salt
        port: 4506
  {{- end }}
{{- end }}

