# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the wsgi module

TOP    = ..

SUBDIR = wsgi

FILES = __init__ app package_push \
	 xmlrpc wsgiHandler wsgiRequest

include $(TOP)/Makefile.defs
