# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: MIT

FROM registry.opensuse.org/systemsmanagement/uyuni/master/docker/containers/uyuni-master-testsuite
RUN zypper --non-interactive in avahi
