# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the rhnSQL module
#

TOP     = ../..
SUBDIR	= server/rhnSQL

SPACEWALK_FILES	= __init__ sql_base sql_lib \
	  sql_row sql_sequence sql_table sql_types \
          dbi driver_postgresql const

include $(TOP)/Makefile.defs
