#!/bin/bash

# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: MIT

if [ ! -e /etc/postfix/postfix.configured ]; then
	echo "First configuration of postfix"
        /usr/sbin/config.postfix
        touch /etc/postfix/postfix.configured
fi
