#!/bin/bash

REPORTDB_NAME=reportdb

run_sql() {
    PGHOST= PGHOSTADDR= psql -v ON_ERROR_STOP=1 -U "$POSTGRES_USER" --no-password --no-psqlrc "$@"
}

echo "CREATE DATABASE $REPORTDB_NAME ENCODING = UTF8 ;" | run_sql
echo "CREATE ROLE $REPORTDB_USER PASSWORD '$REPORTDB_PASSWORD' NOSUPERUSER NOCREATEDB CREATEROLE INHERIT LOGIN;" | run_sql -d $REPORTDB_NAME
echo "GRANT ALL PRIVILEGES ON DATABASE $REPORTDB_NAME TO $REPORTDB_USER;" | run_sql -d $REPORTDB_NAME
echo "GRANT ALL PRIVILEGES ON SCHEMA public TO $REPORTDB_USER;" | run_sql -d $REPORTDB_NAME
