# Makefile for the xmlrpc module
#

TOP	= ../../..
SUBDIR	= server/handlers/xmlrpc

FILES	= __init__ country queue registration states up2date errata \
	  getMethod proxy get_handler scap

include $(TOP)/Makefile.defs

