FROM ghcr.io/jordimassaguerpla/uyuni/server-search-dev:master
#TODO:
#RUN  make build and make install
#COPY files
#CMD /usr/sbin/rhn-search
#simulate a server
CMD ncat -l 2000 --keep-open --exec /bin/cat
