#!/bin/sh

if [[ $@ =~ "-h" ]] || [[ $@ =~ "--help" ]] || [ $# -ne 1 -o $# -gt 1 ]; then
        echo "Usage: `basename $0` -h | --help | output-file"
        exit
fi

if [ "$(spacewalk-cfg-get db_backend)" = "postgresql" ]; then
        sql="
SHOW ALL;
"
fi

output=$(echo "$sql" | spacewalk-sql --select-mode -)

if [ "$1" = "-" ]; then
        echo "$output"
else
        echo "$output" > $1
fi
