#!ExclusiveArch: do-not-build
#!ForceMultiVersion

# SPDX-FileCopyrightText: 2026 SUSE LLC
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 SUSE LLC

# For this container we only build the Dockerfile.$flavor builds.
