# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: MIT

whitelistObjectNames:
  - java.lang:type=Threading,*
  - java.lang:type=Memory,*
  - Catalina:type=ThreadPool,name=*
rules:
  - pattern: ".*"
