# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

#
# Makefile for proxy/wsgi
#

TOP	= ..
SUBDIR	= wsgi
FILES	= xmlrpc xmlrpc_redirect
include $(TOP)/Makefile.defs

