#!/bin/sh
# Generates the Rancher questions.yml from the x-rancher-question annotations
# that helm-schema copies from values.yaml into values.schema.json.
#
# Run helm-schema first so that values.schema.json is up to date.
#
# Annotation fields (an object, or a list of objects):
#   label, order        required
#   group               required, except for subquestions
#   variable            path relative to the annotated key, needed for keys using $ref
#   subquestion_of      variable of the parent question
#   type, description, default
#                       override the values inferred from the schema and values.yaml
#   empty_option_label  label of the "" enum option, "None" by default
# Any other field is copied as is (required, min, max, show_if, show_subquestion_if...)

set -e

cd "$(dirname "$0")"

VALUES_JSON=$(yq -o json values.yaml)

# Not piped directly to yq: set -e would miss the jq errors.
QUESTIONS_JSON=$(jq --argjson values "$VALUES_JSON" '
# An annotation is either a single question or a list of questions.
def as_list: if type == "array" then .[] else . end;

def fail_if(condition; message): if condition then error(message) end;

def drop_nulls: with_entries(select(.value != null));

def infer_type($schema; $value):
  if $schema.enum then "enum"
  elif $schema.type == "boolean" or ($value | type) == "boolean" then "boolean"
  elif $schema.type == "integer" or ($value | type) == "number" then "int"
  else "string" end;

# The Rancher dashboard shows a "" option as {"label":""}: use the value: label map form to name it.
def label_empty_option($empty_label):
  if type == "array" and any(.[]; . == "") then
    map({key: ., value: (if . == "" then $empty_label else . end)}) | from_entries
  end;

# One entry per question annotated in the schema, with the annotated key path in values.yaml.
def annotated_keys:
  paths(objects | has("x-rancher-question")) as $schema_path
  | getpath($schema_path) as $key_schema
  | {
      key_path: ($schema_path | map(select(. != "properties"))),
      key_schema: $key_schema,
      annotation: ($key_schema["x-rancher-question"] | as_list)
    };

def to_question($values):
  . as
    {
      key_path: $key_path,
      key_schema: $key_schema,
      annotation: $annotation
    }
  | ($key_path + ($annotation.variable // "" | split("."))) as $value_path
  | ($value_path | join(".")) as $variable
  | ($values | getpath($value_path)) as $value
  # A relative variable points inside the annotated key: its schema does not describe the value.
  | (if $annotation.variable then {} else $key_schema end) as $value_schema
  | fail_if($annotation.label == null; "\($variable): missing label")
  | fail_if($annotation.order == null; "\($variable): missing order")
  | fail_if($annotation.group == null and $annotation.subquestion_of == null; "\($variable): missing group")
  | {
      variable: $variable,
      label: $annotation.label,
      description: ($annotation.description // $value_schema.description),
      type: ($annotation.type // infer_type($value_schema; $value)),
      default: (if $annotation | has("default") then $annotation.default else $value end),
      options: (
        if ($annotation.type // "enum") == "enum" then
          $annotation.options // $value_schema.enum | label_empty_option($annotation.empty_option_label // "None")
        else null end)
    }
    + ($annotation | del(.variable, .label, .description, .type, .default, .options, .empty_option_label))
  | drop_nulls;

def is_subquestion: .subquestion_of != null;

# Rancher only supports one level of subquestions.
def validate_subquestions:
  map(.variable) as $variables
  | map(select(is_subquestion) | .subquestion_of) as $parents
  | map(
      fail_if(is_subquestion and (.subquestion_of | IN($variables[]) | not);
        "\(.variable): unknown subquestion_of \(.subquestion_of)")
      | fail_if(is_subquestion and (.variable | IN($parents[]));
        "\(.variable): subquestions cannot have subquestions")
    );

# Sorts the questions and nests the subquestions under their parent, without the internal fields.
def to_questions_file:
  map(select(is_subquestion)) as $subquestions
  | {
      questions: [
        map(select(is_subquestion | not)) | sort_by(.order)[]
        | .variable as $parent
        | [$subquestions[] | select(.subquestion_of == $parent)] as $children
        | del(.order)
        | if $children != [] then
            .subquestions = ($children | sort_by(.order) | map(del(.order, .subquestion_of, .group)))
          end
      ]
    };

[annotated_keys | to_question($values)]
| validate_subquestions
| to_questions_file
' values.schema.json)

{
  echo "# Generated by gen-questions.sh from the x-rancher-question annotations in values.yaml."
  echo "# Do not edit, run helm-schema and gen-questions.sh instead."
  printf '%s\n' "$QUESTIONS_JSON" | yq -p json -o yaml
} >questions.yml
