#!/bin/bash

# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: Apache-2.0

/usr/bin/spacewalk-debug --no-compression --dir $1
echo "Done, SUSE Manager logs can now be found in the supportconfig directory."

