.TH susemanager-plugin "8" "04 Apr 2013" "susemanager-plugin" "Support Utilities Manual"
.SH NAME
susemanager-plugin \- SUSE Manager Plugin for 
.BR supportconfig (8)
.
.SH DESCRIPTION
Supportconfig plugins add functionality to the supportconfig script. This plugin extends supportconfig's functionality to include SUSE Manager
information. Supportconfig saves the plugin output as plugin-susemanager.txt.

.SH FILES
.I /usr/lib/supportconfig/plugins/susemanager
.RS
The SUSE Manager plugin
.RE
.SH AUTHOR
Stefan Bogner <sbogner@suse.com>
.SH SEE ALSO
.BR supportconfig (8)
.BR supportconfig.conf (5)
