#!/bin/bash
#############################################################
# Name:        Supportconfig Plugin for SUSE Multi-Linux Manager
# Description: Gathers important troubleshooting information
#              about SUSE Multi-Linux Manager
# License:     GPLv2
# Author:      Stefan Bogner <sbogner@suse.com>
#              Michael Calmer <mc@suse.com>
# Modified:    2026 April 18
#############################################################

SVER=5.2.0
RCFILE="/usr/lib/supportconfig/resources/supportconfig.rc"
OF='plugin-susemanager.txt'

[ -s $RCFILE ] && . $RCFILE || { echo "ERROR: Initializing resource file: $RCFILE"; exit 1; }

log_write $OF
log_entry $OF note "Supportconfig Plugin for SUSE Multi-Linux Manager, v${SVER}"
addHeaderFile $OF

log_cmd $OF "grep web.version /usr/share/rhn/config-defaults/rhn_web.conf"

log_cmd $OF "echo $HOSTNAME"

RPMLIST="
salt
salt-master
susemanager
susemanager-schema
susemanager-tools
"
DAEMONLIST="tomcat taskomatic rhn-search cobblerd apache2 salt-api salt-master"

if ! rpm -q susemanager &>/dev/null; then
  echo "ERROR: SUSE Multi-Linux Manager package(s) not installed"
  echo
  exit 111
fi

for THISRPM in $RPMLIST
do
   rpm_verify $OF $THISRPM
done

for i in $DAEMONLIST
do
    log_cmd $OF "systemctl status $i"
done

log_cmd $OF "/bin/ls -l --time-style=long-iso /usr/local/lib"
log_cmd $OF "/bin/ls -l --time-style=long-iso /usr/local/lib64"

log_cmd $OF "find /usr/share/susemanager/www/tomcat/webapps/rhn/WEB-INF/lib/ | xargs file | grep broken"
log_cmd $OF "find /usr/share/spacewalk/taskomatic/ | xargs file | grep broken"
log_cmd $OF "find /usr/share/rhn/search/lib/ | xargs file | grep broken"

log_entry $OF note "SSL Configuration"

DOCUMENTROOT=$(spacewalk-cfg-get documentroot)
ROOT_CA_CERT="/etc/pki/trust/anchors/LOCAL-RHN-ORG-TRUSTED-SSL-CERT"
DB_ROOT_CA_CERT="/etc/pki/trust/anchors/DB-RHN-ORG-TRUSTED-SSL-CERT"
SERVER_CERT="/etc/pki/tls/certs/spacewalk.crt"

conf_files $OF $DOCUMENTROOT/pub/RHN-ORG-TRUSTED-SSL-CERT \
            $ROOT_CA_CERT \
            $DB_ROOT_CA_CERT \
            $SERVER_CERT
log_cmd $OF "/bin/ls -l --time-style=long-iso /etc/ssl/certs/"

log_cmd $OF "/bin/ls -l --time-style=long-iso $DOCUMENTROOT/pub/ | grep -i trusted"

log_entry $OF note "SSL Certificate Details"

log_certificate_details() {
    CERT_LABEL="$1"
    CERT_PATH="$2"
    log_write $OF "--- $CERT_LABEL ($CERT_PATH) ---"

    if [ ! -f "$CERT_PATH" ]; then
        log_write $OF "Certificate file not found"
        return
    fi

    CERT_INDEX=1
    exec 3< "$CERT_PATH"
    while CERT_PEM=$(openssl x509 <&3 2>/dev/null); do
        log_write $OF "Certificate $CERT_INDEX:"
        log_cmd $OF "echo \"$CERT_PEM\" | openssl x509 -noout -subject -issuer -dates -fingerprint -sha256 -ext basicConstraints"
        if echo "$CERT_PEM" | openssl x509 -checkend 0 > /dev/null 2>&1; then
            if ! echo "$CERT_PEM" | openssl x509 -checkend 2592000 > /dev/null 2>&1; then
                log_write $OF "*** WARNING: Certificate $CERT_INDEX expires within 30 days ***"
            fi
        else
            log_write $OF "*** WARNING: CERTIFICATE $CERT_INDEX IS EXPIRED ***"
        fi
        CERT_INDEX=$((CERT_INDEX + 1))
    done
    exec 3<&-
}

log_certificate_details "Root CA" "$ROOT_CA_CERT"
log_certificate_details "DB Root CA" "$DB_ROOT_CA_CERT"
log_certificate_details "Server Certificate" "$SERVER_CERT"

log_entry $OF note "SSL Certificate Chain & FQDN Validation"

FQDN=$(sed -n 's/^[[:space:]]*java\.hostname[[:space:]]*=[[:space:]]*//p' /etc/rhn/rhn.conf 2>/dev/null | sed 's/[[:space:]]*$//' | tail -1)
log_write $OF "Configured FQDN (from rhn.conf): $FQDN"

if [ -f "$ROOT_CA_CERT" ] && [ -f "$SERVER_CERT" ]; then
    if [ -n "$FQDN" ]; then
        log_cmd $OF "openssl verify -CAfile $ROOT_CA_CERT -untrusted $SERVER_CERT -verify_hostname $FQDN $SERVER_CERT"
    else
        log_write $OF "*** WARNING: Could not determine configured FQDN from /etc/rhn/rhn.conf ***"
        log_cmd $OF "openssl verify -CAfile $ROOT_CA_CERT -untrusted $SERVER_CERT $SERVER_CERT"
    fi
else
    log_write $OF "Cannot validate chain: one or more certificate files missing"
fi

log_entry $OF note "Crypto Policy"

if [ -f /etc/crypto-policies/config ]; then
	log_cmd $OF "cat /etc/crypto-policies/config"
elif [ $(cat /proc/sys/crypto/fips_enabled) -ne 0 ]; then
	log_write $OF "FIPS"
else
	log_cmd $OF "grep -v '#' /usr/share/crypto-policies/default-config"
fi


log_cmd $OF "/usr/lib/susemanager/bin/susemanager-connection-check"
log_cmd $OF "salt-master --versions-report"

log_cmd $OF "spacewalk-sql --select-mode-direct - <<< \"select username scc_org from susecredentials sc where sc.type = 'scc';\""

log_write $OF "# Number of elements in table susesaltevent. If the next number is too high, please verify the large scale tuning guide property 'java.salt_event_thread_pool_size'."
log_cmd $OF "spacewalk-sql --select-mode-direct - <<< \"select count(*) from susesaltevent;\""
log_cmd $OF "grep \"Client bootstrap script\" /srv/www/htdocs/pub/bootstrap/*.sh"

log_entry $OF note "Cloud / PAYG"
if [ -x /usr/bin/instance-flavor-check ]; then
        log_cmd $OF "/usr/bin/instance-flavor-check"
        if [ $(/usr/bin/instance-flavor-check) == "PAYG" ]; then
                rpm_verify $OF "python-instance-billing-flavor-check"
                rpm_verify $OF "billing-data-service"
                rpm_verify $OF "csp-billing-adapter-service"
                rpm_verify $OF "python311-csp-billing-adapter"
                rpm_verify $OF "python311-csp-billing-adapter-local"
                rpm_verify $OF "python311-csp-billing-adapter-amazon"
                rpm_verify $OF "suma-amazon-adapter-config-llc"
                rpm_verify $OF "suma-amazon-adapter-config-ltd"
                rpm_verify $OF "python311-csp-billing-adapter-azure"
                rpm_verify $OF "suma-azure-adapter-config-llc"
                rpm_verify $OF "suma-azure-adapter-config-ltd"
        else
                log_write $OF "Not a PAYG Instance"
        fi
else
        log_write $OF "Not a Cloud Instance"
fi

log_cmd $OF "/sbin/supportconfig-sumalog $LOG"
log_cmd $OF "cp /var/log/zypper.log $LOG"
