= Software Crashes

If you're using / have installed abrt (http://abrt.readthedocs.org/) on your systems registered to {productname}, you may take advantage of the software crash reporting functionality provided by Spacewalk.

[IMPORTANT]
====
Crash reporting functionality only works with {rhel} traditionally managed clients. (no Salt)
Crash reporting functionality works with {rhnminrelease6} or higher only.
====

This functionality allows:

* Registered clients to automatically report software crashes captured by abrt directly to the Spacewalk server
* Processing captured crashes in a centralized way
** View software crashes that occurred on a system
** Manipulate crash files captured with a crash (further processing, reporting a bug)
** You may add custom notes to a particular crash
** You can group similar software crashes across multiple systems in an organization
** Create crash reports with spacewalk-report



== Quickstart

To use the software crash reporting functionality:

. Install spacewalk-abrt package (part of Spacewalk client repository) on your client system(s). This package will install abrt as its dependency. Note: neither abrt nor spacewalk-abrt are available for RHEL-5 / CentOS-5.

. Wait for a software crash to occur or trigger a crash manually:
+
----
$ sleep 60 & $ kill -s SEGV %1 [1]+ Segmentation fault sleep 60
----

. In your webui, navigate to:
+
----
Systems -> [desired system] -> Software -> Software Crashes
----
+
From this page you can view the list of software crashes that occurred on the registered system. Click on the particular crash to see the crash details and crash files captured for this crash report.

. Use the following API calls to manipulate with the reported software crashes:
+
----
system.crash.getLastReportDate()
system.crash.getUniqueCrashCount()
system.crash.getTotalCrashCount()
system.crash.listSystemCrashes()
system.crash.listSystemCrashFiles()
system.crash.deleteCrash()
system.crash.getCrashFileUrl()
system.crash.getCrashFile()
----

Consult the API documentation for further details.



== Advanced Usage

You can now create custom crash notes (adding / viewing / removing).

To manipulate with the crash notes in the webui, navigate to:

----
Systems -> [desired system] -> Software -> Software Crashes -> [desired software crash] -> Crash Notes
----

To manipulate with the crash notes using the API, use the following calls:

----
system.crash.createCrashNote()
system.crash.deleteCrashNote()
system.crash.getCrashNotesForCrash()
----



== Organization Configuration

{productname} allows you to configure the following crash-related settings in your organization:

* Turn the crash reporting on / off
* Turn the crash file upload on / off
* Crash file upload size limit, i.e. the size of a single crash file that can be uploaded with every crash report

To configure these settings in webui, navigate to:

----
Admin -> | [your organization] | -> Configuration
----


You can also use the following API calls to configure your organization:

----
org.getCrashFileSizeLimit()
org.setCrashFileSizeLimit()
org.isCrashReportingEnabled()
org.setCrashReporting()
org.isCrashfileUploadEnabled()
org.setCrashfileUpload()
----



== Reporting

{productname} allows you to use the following crash-related reports with the spacewalk-report tool:

----
system-crash-count
system-crash-details
----

