name: Insert Test Runs into DB (Scheduled)

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  insert-test-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Debug step
        run: echo "Workflow is running successfully"