# SPDX-FileCopyrightText: 2026 Red Hat, Inc.
# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the xmlrpc handlers
#

TOP	= ../..
SUBDIR	= server/handlers

FILES	= __init__

SUBDIRS = \
		  app \
		  xmlrpc

include $(TOP)/Makefile.defs

