/*
 * Copyright (c) 2026 SUSE LLC
 *
 * This software is licensed to you under the GNU General Public License,
 * version 2 (GPLv2). There is NO WARRANTY for this software, express or
 * implied, including the implied warranties of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
 * along with this software; if not, see
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
 */
package com.redhat.rhn.frontend.xmlrpc.activationkey;

import com.redhat.rhn.domain.config.ConfigChannel;
import com.redhat.rhn.domain.token.ActivationKey;
import com.redhat.rhn.domain.user.User;
import com.redhat.rhn.frontend.xmlrpc.kickstart.profile.keys.KeysHandlerApi;
import com.redhat.rhn.frontend.xmlrpc.system.config.ServerConfigHandlerApi;

import com.suse.manager.api.ApiResponseWrapper;
import com.suse.manager.api.docs.ApiEndpointDoc;
import com.suse.manager.api.docs.LegacyDocResponse;
import com.suse.manager.api.docs.PublicApiEndpoint;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Date;
import java.util.List;
import java.util.Map;

import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.extensions.Extension;
import io.swagger.v3.oas.annotations.extensions.ExtensionProperty;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.tags.Tag;
import spark.route.HttpMethod;

/**
 * API contract for {@link ActivationKeyHandler}.
 */
@Tag(name = "activationkey",
    description = "Contains methods to access common activation key functions available " +
        "from the web interface.")
public interface ActivationKeyHandlerApi {

    /**
     * Creates an activation key with a usage limit.
     *
     * @param loggedInUser the current user
     * @param key the key, or an empty string to have one autogenerated
     * @param description the description of the key
     * @param baseChannelLabel the label of the base channel
     * @param usageLimit the usage limit of the key
     * @param entitlements the add-on system type labels
     * @param universalDefault whether the key is the organization default
     * @return the new activation key
     */
    @ApiEndpointDoc(
        summary = "Create a new activation key. The activation key parameter passed in will be " +
            "prefixed with the organization ID, and this value will be returned from the create " +
            "call. Eg. If the caller passes in the key \"foo\" and belong to an organization with " +
            "the ID 100, the actual activation key will be \"100-foo\". This call allows for the " +
            "setting of a usage limit on this activation key. If unlimited usage is desired see " +
            "the similarly named API method with no usage limit argument.",
        requestClass = CreateKeyWithUsageLimitRequest.class,
        responseClass = StringResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "The new activation key")
    )
    String create(User loggedInUser, String key, String description, String baseChannelLabel,
            Integer usageLimit, List<String> entitlements, Boolean universalDefault);

    /**
     * Lists the channels of an activation key with temporary authentication tokens.
     *
     * @param minionId the id of the minion to authenticate with
     * @param machinePassword the password specific to the machine
     * @param activationKey the activation key to use channels from
     * @return the channels of the activation key
     */
    @PublicApiEndpoint
    @ApiEndpointDoc(
        summary = "List the channels for the given activation key with temporary authentication " +
            "tokens to access them. Authentication is done via a machine specific password.",
        method = HttpMethod.get,
        responseClass = ChannelInfoListResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "channelInfo")
    )
    List<ChannelInfo> listChannels(
        @Parameter(name = "minionId", in = ParameterIn.QUERY, required = true,
                description = "The id of the minion to authenticate with.") String minionId,
        @Parameter(name = "machinePassword", in = ParameterIn.QUERY, required = true,
                description = "password specific to a machine.") String machinePassword,
        @Parameter(name = "activationKey", in = ParameterIn.QUERY, required = true,
                description = "activation key to use channels from.") String activationKey);

    /**
     * Clones an activation key.
     *
     * @param loggedInUser the current user
     * @param key the key to be cloned
     * @param cloneDescription the description of the cloned key
     * @return the new activation key
     */
    @ApiEndpointDoc(
        summary = "Clone an existing activation key.",
        requestClass = CloneKeyRequest.class,
        responseClass = StringResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "The new activation key")
    )
    String clone(User loggedInUser, String key, String cloneDescription);

    /**
     * Creates an activation key with unlimited usage.
     *
     * @param loggedInUser the current user
     * @param key the key, or an empty string to have one autogenerated
     * @param description the description of the key
     * @param baseChannelLabel the label of the base channel
     * @param entitlements the add-on entitlement labels
     * @param universalDefault whether the key is the organization default
     * @return the new activation key
     */
    @ApiEndpointDoc(
        summary = "Create a new activation key with unlimited usage. The activation key parameter " +
            "passed in will be prefixed with the organization ID, and this value will be returned " +
            "from the create call. Eg. If the caller passes in the key \"foo\" and belong to an " +
            "organization with the ID 100, the actual activation key will be \"100-foo\".",
        requestClass = CreateKeyRequest.class,
        responseClass = StringResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "The new activation key")
    )
    String create(User loggedInUser, String key, String description, String baseChannelLabel,
            List<String> entitlements, Boolean universalDefault);

    /**
     * Deletes an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Delete an activation key.",
        requestClass = KeyRequest.class,
        isIntegerResponse = true
    )
    int delete(User loggedInUser, String key);

    /**
     * Updates the details of an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param details the details to set
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Update the details of an activation key.",
        requestClass = SetDetailsRequest.class,
        isIntegerResponse = true
    )
    int setDetails(User loggedInUser, String key, Map<String, Object> details);

    /**
     * Looks up the details of an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @return the details of the activation key
     */
    @ApiEndpointDoc(
        summary = "Lookup an activation key's details.",
        method = HttpMethod.get,
        responseClass = ActivationKeyResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "activation key")
    )
    ActivationKey getDetails(
        @Parameter(hidden = true) User loggedInUser,
        @Parameter(name = "key", in = ParameterIn.QUERY, required = true) String key);

    /**
     * Adds add-on system types to an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param entitlements the add-on system type labels
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Add add-on System Types to an activation key.",
        requestClass = EntitlementsRequest.class,
        isIntegerResponse = true
    )
    int addEntitlements(User loggedInUser, String key, List<String> entitlements);

    /**
     * Removes entitlements from an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param entitlements the entitlement labels
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Remove entitlements (by label) from an activation key. Currently only " +
            "virtualization_host add-on entitlement is permitted.",
        requestClass = RemoveEntitlementsRequest.class,
        isIntegerResponse = true
    )
    int removeEntitlements(User loggedInUser, String key, List<String> entitlements);

    /**
     * Adds child channels to an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param childChannelLabels the labels of the child channels
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Add child channels to an activation key.",
        requestClass = ChildChannelsRequest.class,
        isIntegerResponse = true
    )
    int addChildChannels(User loggedInUser, String key, List<String> childChannelLabels);

    /**
     * Removes child channels from an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param childChannelLabels the labels of the child channels
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Remove child channels from an activation key.",
        requestClass = ChildChannelsRequest.class,
        isIntegerResponse = true
    )
    int removeChildChannels(User loggedInUser, String key, List<String> childChannelLabels);

    /**
     * Adds server groups to an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param serverGroupIds the ids of the server groups
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Add server groups to an activation key.",
        requestClass = ServerGroupsRequest.class,
        isIntegerResponse = true
    )
    int addServerGroups(User loggedInUser, String key, List<Integer> serverGroupIds);

    /**
     * Removes server groups from an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param serverGroupIds the ids of the server groups
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Remove server groups from an activation key.",
        requestClass = ServerGroupsRequest.class,
        isIntegerResponse = true
    )
    int removeServerGroups(User loggedInUser, String key, List<Integer> serverGroupIds);

    /**
     * Adds packages to an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param packages the packages to add
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Add packages to an activation key.",
        requestClass = PackagesRequest.class,
        isIntegerResponse = true
    )
    int addPackages(User loggedInUser, String key, List<Map<String, String>> packages);

    /**
     * Removes package names from an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param packages the packages to remove
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Remove package names from an activation key.",
        requestClass = PackagesRequest.class,
        isIntegerResponse = true
    )
    int removePackages(User loggedInUser, String key, List<Map<String, String>> packages);

    /**
     * Adds app streams to an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param appStreams the app streams to add
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Add app streams to an activation key. If any of the provided app streams is " +
            "not available in the channels of the activation key, the request will fail.",
        requestClass = AppStreamsRequest.class,
        isIntegerResponse = true
    )
    int addAppStreams(User loggedInUser, String key, List<Map<String, String>> appStreams);

    /**
     * Removes app streams from an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @param appStreams the app streams to remove
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Remove app streams from an activation key.",
        requestClass = AppStreamsRequest.class,
        isIntegerResponse = true
    )
    int removeAppStreams(User loggedInUser, String key, List<Map<String, String>> appStreams);

    /**
     * Lists the activation keys visible to the user.
     *
     * @param loggedInUser the current user
     * @return the visible activation keys
     */
    @ApiEndpointDoc(
        summary = "List activation keys that are visible to the user.",
        method = HttpMethod.get,
        responseClass = KeysHandlerApi.ActivationKeyListResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "activation key")
    )
    List<ActivationKey> listActivationKeys(@Parameter(hidden = true) User loggedInUser);

    /**
     * Lists the systems activated with an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @return the activated systems
     */
    @ApiEndpointDoc(
        summary = "List the systems activated with the key provided.",
        method = HttpMethod.get,
        responseClass = ActivatedSystemListResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "system structure")
    )
    Object[] listActivatedSystems(
        @Parameter(hidden = true) User loggedInUser,
        @Parameter(name = "key", in = ParameterIn.QUERY, required = true) String key);

    /**
     * Lists the configuration channels of an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @return the configuration channels
     */
    @ApiEndpointDoc(
        summary = "List configuration channels associated to an activation key.",
        method = HttpMethod.get,
        responseClass = ServerConfigHandlerApi.ConfigChannelListResponse.class,
        legacyDocResponse = @LegacyDocResponse(name = "configuration channel information")
    )
    List<ConfigChannel> listConfigChannels(
        @Parameter(hidden = true) User loggedInUser,
        @Parameter(name = "key", in = ParameterIn.QUERY, required = true) String key);

    /**
     * Replaces the configuration channels of the given activation keys.
     *
     * @param loggedInUser the current user
     * @param keys the activation keys
     * @param configChannelLabels the labels of the configuration channels
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Replace the existing set of configuration channels on the given activation keys. " +
            "Channels are ranked by their order in the array.",
        requestClass = SetConfigChannelsRequest.class,
        isIntegerResponse = true
    )
    int setConfigChannels(User loggedInUser, List<String> keys, List<String> configChannelLabels);

    /**
     * Adds configuration channels to the given activation keys.
     *
     * @param loggedInUser the current user
     * @param keys the activation keys
     * @param configChannelLabels the labels of the configuration channels
     * @param addToTop whether the channels are prepended
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Given a list of activation keys and configuration channels, this method adds " +
            "given configuration channels to either the top or the bottom (whichever you specify) " +
            "of an activation key's configuration channels list. The ordering of the configuration " +
            "channels provided in the add list is maintained while adding. If one of the " +
            "configuration channels in the 'add' list already exists in an activation key, the " +
            "configuration channel will be re-ranked to the appropriate place.",
        requestClass = AddConfigChannelsRequest.class,
        isIntegerResponse = true
    )
    int addConfigChannels(User loggedInUser, List<String> keys, List<String> configChannelLabels,
            Boolean addToTop);

    /**
     * Removes configuration channels from the given activation keys.
     *
     * @param loggedInUser the current user
     * @param keys the activation keys
     * @param configChannelLabels the labels of the configuration channels
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Remove configuration channels from the given activation keys.",
        requestClass = SetConfigChannelsRequest.class,
        isIntegerResponse = true
    )
    int removeConfigChannels(User loggedInUser, List<String> keys, List<String> configChannelLabels);

    /**
     * Enables configuration file deployment for an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Enable configuration file deployment for the specified activation key.",
        requestClass = KeyRequest.class,
        isIntegerResponse = true
    )
    int enableConfigDeployment(User loggedInUser, String key);

    /**
     * Disables configuration file deployment for an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @return 1 on success
     */
    @ApiEndpointDoc(
        summary = "Disable configuration file deployment for the specified activation key.",
        requestClass = KeyRequest.class,
        isIntegerResponse = true
    )
    int disableConfigDeployment(User loggedInUser, String key);

    /**
     * Checks the configuration file deployment status of an activation key.
     *
     * @param loggedInUser the current user
     * @param key the activation key
     * @return the deployment status
     */
    @ApiEndpointDoc(
        summary = "Check configuration file deployment status for the activation key specified.",
        requestClass = KeyRequest.class,
        isIntegerResponse = true,
        responseDescription = "1 if enabled, 0 if disabled, exception thrown otherwise",
        legacyDocResponse = @LegacyDocResponse(name = "status")
    )
    int checkConfigDeployment(User loggedInUser, String key);

    @Schema(name = "ApiResponseString")
    interface StringResponse extends ApiResponseWrapper<String> { }

    @Schema(name = "ApiResponseChannelInfoList")
    interface ChannelInfoListResponse extends ApiResponseWrapper<List<ChannelInfoDoc>> { }

    @Schema(name = "ApiResponseActivationKey")
    interface ActivationKeyResponse extends ApiResponseWrapper<KeysHandlerApi.ActivationKeyDoc> { }

    @Schema(name = "ApiResponseActivatedSystemList")
    interface ActivatedSystemListResponse extends ApiResponseWrapper<List<ActivatedSystemDoc>> { }

    @Schema(name = "ActivationKeyKeyRequest")
    interface KeyRequest {

        /**
         * @return the activation key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();
    }

    @Schema(name = "ActivationKeyCreateWithUsageLimitRequest")
    @JsonPropertyOrder({"key", "description", "baseChannelLabel", "usageLimit", "entitlements",
        "universalDefault"})
    interface CreateKeyWithUsageLimitRequest {

        /**
         * @return the activation key
         */
        @Schema(description = "Leave empty to have new key autogenerated.",
                requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the description of the key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getDescription();

        /**
         * @return the label of the base channel
         */
        @Schema(description = "Leave empty to accept default.",
                requiredMode = Schema.RequiredMode.REQUIRED)
        String getBaseChannelLabel();

        /**
         * @return the usage limit of the key
         */
        @Schema(description = "If unlimited usage is desired, use the create API that does not " +
                "include the parameter.", requiredMode = Schema.RequiredMode.REQUIRED)
        Integer getUsageLimit();

        /**
         * @return the add-on system type labels
         */
        @ArraySchema(
            arraySchema = @Schema(description = "Add-on system type labels to associate with the key.",
                    requiredMode = Schema.RequiredMode.REQUIRED),
            schema = @Schema(allowableValues = {"container_build_host", "monitoring_entitled",
                "osimage_build_host", "virtualization_host", "ansible_control_node", "proxy_entitled"}))
        List<String> getEntitlements();

        /**
         * @return whether the key is the organization default
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        Boolean getUniversalDefault();
    }

    @Schema(name = "ActivationKeyCreateRequest")
    @JsonPropertyOrder({"key", "description", "baseChannelLabel", "entitlements", "universalDefault"})
    interface CreateKeyRequest {

        /**
         * @return the activation key
         */
        @Schema(description = "Leave empty to have new key autogenerated.",
                requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the description of the key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getDescription();

        /**
         * @return the label of the base channel
         */
        @Schema(description = "Leave empty to accept default.",
                requiredMode = Schema.RequiredMode.REQUIRED)
        String getBaseChannelLabel();

        /**
         * @return the add-on entitlement labels
         */
        @ArraySchema(
            arraySchema = @Schema(description = "Add-on entitlement label to associate with the key.",
                    requiredMode = Schema.RequiredMode.REQUIRED),
            schema = @Schema(allowableValues = {"virtualization_host"}))
        List<String> getEntitlements();

        /**
         * @return whether the key is the organization default
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        Boolean getUniversalDefault();
    }

    @Schema(name = "ActivationKeyCloneRequest")
    @JsonPropertyOrder({"key", "cloneDescription"})
    interface CloneKeyRequest {

        /**
         * @return the key to be cloned
         */
        @Schema(description = "Key to be cloned.", requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the description of the cloned key
         */
        @Schema(description = "Description of the cloned key.",
                requiredMode = Schema.RequiredMode.REQUIRED)
        String getCloneDescription();
    }

    @Schema(name = "ActivationKeySetDetailsRequest")
    @JsonPropertyOrder({"key", "details"})
    interface SetDetailsRequest {

        /**
         * @return the activation key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the details to set
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        ActivationKeyDetailsDoc getDetails();
    }

    @Schema(name = "ActivationKeyDetails", description = "details")
    @JsonPropertyOrder({"description", "baseChannelLabel", "usageLimit", "unlimitedUsageLimit",
        "universalDefault", "disabled", "contactMethod"})
    interface ActivationKeyDetailsDoc {

        /**
         * @return the description of the key
         */
        @Schema(description = "optional")
        String getDescription();

        /**
         * @return the label of the base channel
         */
        @Schema(name = "base_channel_label",
                description = "optional - to set default base channel set to empty string or 'none'")
        String getBaseChannelLabel();

        /**
         * @return the usage limit of the key
         */
        @Schema(name = "usage_limit", description = "optional")
        Integer getUsageLimit();

        /**
         * @return whether the usage is unlimited
         */
        @Schema(name = "unlimited_usage_limit",
                description = "Set true for unlimited usage and to override usage_limit")
        Boolean getUnlimitedUsageLimit();

        /**
         * @return whether the key is the organization default
         */
        @Schema(name = "universal_default", description = "optional")
        Boolean getUniversalDefault();

        /**
         * @return whether the key is disabled
         */
        @Schema(description = "optional")
        Boolean getDisabled();

        /**
         * @return the contact method
         */
        @Schema(name = "contact_method", description = "One of the following:",
                allowableValues = {"default", "ssh-push", "ssh-push-tunnel"})
        String getContactMethod();
    }

    @Schema(name = "ActivationKeyEntitlementsRequest")
    @JsonPropertyOrder({"key", "entitlements"})
    interface EntitlementsRequest {

        /**
         * @return the activation key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the add-on system type labels
         */
        @ArraySchema(
            arraySchema = @Schema(description = "Add-on system type labels to associate with the key.",
                    requiredMode = Schema.RequiredMode.REQUIRED),
            schema = @Schema(allowableValues = {"container_build_host", "monitoring_entitled",
                "osimage_build_host", "virtualization_host", "ansible_control_node", "proxy_entitled"}))
        List<String> getEntitlements();
    }

    @Schema(name = "ActivationKeyRemoveEntitlementsRequest")
    @JsonPropertyOrder({"key", "entitlements"})
    interface RemoveEntitlementsRequest {

        /**
         * @return the activation key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the entitlement labels
         */
        @ArraySchema(
            arraySchema = @Schema(requiredMode = Schema.RequiredMode.REQUIRED),
            schema = @Schema(allowableValues = {"virtualization_host"}))
        List<String> getEntitlements();
    }

    @Schema(name = "ActivationKeyChildChannelsRequest")
    @JsonPropertyOrder({"key", "childChannelLabels"})
    interface ChildChannelsRequest {

        /**
         * @return the activation key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the labels of the child channels
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getChildChannelLabels();
    }

    @Schema(name = "ActivationKeyServerGroupsRequest")
    @JsonPropertyOrder({"key", "serverGroupIds"})
    interface ServerGroupsRequest {

        /**
         * @return the activation key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the ids of the server groups
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        List<Integer> getServerGroupIds();
    }

    @Schema(name = "ActivationKeyPackagesRequest")
    @JsonPropertyOrder({"key", "packages"})
    interface PackagesRequest {

        /**
         * @return the activation key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the packages
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        @LegacyDocResponse(name = "package")
        List<ActivationKeyPackageDoc> getPackages();
    }

    @Schema(name = "ActivationKeyAppStreamsRequest")
    @JsonPropertyOrder({"key", "appStreams"})
    interface AppStreamsRequest {

        /**
         * @return the activation key
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getKey();

        /**
         * @return the app streams
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        @LegacyDocResponse(name = "Module Stream")
        List<ModuleStreamDoc> getAppStreams();
    }

    @Schema(name = "ActivationKeySetConfigChannelsRequest")
    @JsonPropertyOrder({"keys", "configChannelLabels"})
    interface SetConfigChannelsRequest {

        /**
         * @return the activation keys
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getKeys();

        /**
         * @return the labels of the configuration channels
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getConfigChannelLabels();
    }

    @Schema(name = "ActivationKeyAddConfigChannelsRequest")
    @JsonPropertyOrder({"keys", "configChannelLabels", "addToTop"})
    interface AddConfigChannelsRequest {

        /**
         * @return the activation keys
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getKeys();

        /**
         * @return the labels of the configuration channels
         */
        @Schema(description = "List of configuration channel labels in the ranked order.",
                requiredMode = Schema.RequiredMode.REQUIRED)
        List<String> getConfigChannelLabels();

        /**
         * @return whether the channels are prepended
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED,
                allowableValues = {"true", "false"},
                extensions = @Extension(name = "x-uyuni-doc-option-descriptions", properties = {
                    @ExtensionProperty(name = "true", value = "To prepend the given channels to the " +
                        "beginning of the activation key's config channel list"),
                    @ExtensionProperty(name = "false", value = "To append the given channels to the " +
                        "end of the activation key's config channel list")
                }))
        Boolean getAddToTop();
    }

    @Schema(name = "ActivationKeyPackage", description = "package")
    @JsonPropertyOrder({"name", "arch"})
    interface ActivationKeyPackageDoc {

        /**
         * @return the package name
         */
        @Schema(description = "Package name", requiredMode = Schema.RequiredMode.REQUIRED)
        String getName();

        /**
         * @return the arch label
         */
        @Schema(description = "Arch label - Optional", requiredMode = Schema.RequiredMode.REQUIRED)
        String getArch();
    }

    @Schema(name = "ActivationKeyModuleStream", description = "Module Stream")
    @JsonPropertyOrder({"module", "stream"})
    interface ModuleStreamDoc {

        /**
         * @return the module name
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getModule();

        /**
         * @return the stream name
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getStream();
    }

    @Schema(name = "ChannelInfo", description = "channelInfo")
    @JsonPropertyOrder({"label", "name", "url", "token"})
    interface ChannelInfoDoc {

        /**
         * @return the channel label
         */
        @Schema(description = "Channel label", requiredMode = Schema.RequiredMode.REQUIRED)
        String getLabel();

        /**
         * @return the channel name
         */
        @Schema(description = "Channel name", requiredMode = Schema.RequiredMode.REQUIRED)
        String getName();

        /**
         * @return the channel url
         */
        @Schema(description = "Channel url", requiredMode = Schema.RequiredMode.REQUIRED)
        String getUrl();

        /**
         * @return the channel access token
         */
        @Schema(description = "Channel access token", requiredMode = Schema.RequiredMode.REQUIRED)
        String getToken();
    }

    @Schema(name = "ActivatedSystem", description = "system structure")
    @JsonPropertyOrder({"id", "hostname", "lastCheckin"})
    interface ActivatedSystemDoc {

        /**
         * @return the system id
         */
        @Schema(description = "System id", requiredMode = Schema.RequiredMode.REQUIRED)
        Integer getId();

        /**
         * @return the hostname
         */
        @Schema(requiredMode = Schema.RequiredMode.REQUIRED)
        String getHostname();

        /**
         * @return the last time the server checked in
         */
        @Schema(name = "last_checkin", description = "Last time server successfully checked in",
                requiredMode = Schema.RequiredMode.REQUIRED)
        @LegacyDocResponse(type = "dateTime.iso8601")
        Date getLastCheckin();
    }
}
