# Container used to test java code of SUSE Manager
#
# VERSION               0.2
FROM PARENT_CONTAINER
MAINTAINER Johannes Renner "jrenner@suse.de"

# Ensure /var/cache/zypp/{packages,raw,solv} are empty - this is a workaround for an aufs bug
RUN zypper cc -a

# Make sure the package repository is up to date
RUN zypper --non-interactive --gpg-auto-import-keys ref

# Install needed packages
RUN zypper in -y ant ant-junit java-1_6_0-ibm-devel python spacewalk-backend-sql-postgresql spacewalk-setup sudo susemanager-tools tar

# Install apache-ivy manually (only needed for 1.7)
ADD ivy-2.3.0.jar /usr/share/java/ivy-2.3.0.jar
RUN ln -s /usr/share/java/ivy-2.3.0.jar /usr/share/java/ivy.jar

# Remove contents of /var/cache/zypp/{packages,raw,solv} - this is a workaround for an aufs bug
RUN zypper cc -a
