CREATE TABLE suseSystemOverview (
    id                          NUMERIC NOT NULL CONSTRAINT suseSystemOverview_id_pk PRIMARY KEY,
    server_name                 VARCHAR(128),
    created                     TIMESTAMPTZ NOT NULL,
    creator_name                VARCHAR(64),
    modified                    TIMESTAMPTZ NOT NULL,
    group_count                 NUMERIC,
    channel_id                  NUMERIC,
    channel_labels              VARCHAR(256),
    security_errata             NUMERIC,
    bug_errata                  NUMERIC,
    enhancement_errata          NUMERIC,
    outdated_packages           NUMERIC,
    config_files_with_differences   NUMERIC,
    last_checkin                TIMESTAMPTZ,
    entitlement_level           VARCHAR(256),
    virtual_guest               BOOLEAN,
    virtual_host                BOOLEAN,
    proxy                       BOOLEAN,
    mgr_server                  BOOLEAN,
    selectable                  BOOLEAN,
    extra_pkg_count             NUMERIC,
    requires_reboot             BOOLEAN,
    kickstarting                BOOLEAN,
    actions_count               NUMERIC,
    package_actions_count       NUMERIC,
    unscheduled_errata_count    NUMERIC,
    status_type                 VARCHAR(20)
);
