--
-- Copyright (c) 2025 SUSE LLC
--
-- This software is licensed to you under the GNU General Public License,
-- version 2 (GPLv2). There is NO WARRANTY for this software, express or
-- implied, including the implied warranties of MERCHANTABILITY or FITNESS
-- FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
-- along with this software; if not, see
-- http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
--

CREATE TABLE suseScapContent
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_id        BIGINT NOT NULL
                  CONSTRAINT suse_scap_content_oid_fk
                  REFERENCES web_customer (id)
                  ON DELETE CASCADE,
    name          VARCHAR(255) NOT NULL,
    description   TEXT,
    datastream_file_name TEXT NOT NULL,
    xccdf_file_name TEXT NOT NULL,
    created       TIMESTAMPTZ DEFAULT current_timestamp NOT NULL,
    modified      TIMESTAMPTZ DEFAULT current_timestamp NOT NULL
);

CREATE UNIQUE INDEX suse_scap_content_oid_name_uq
    ON suseScapContent (org_id, name);
