--
-- Copyright (c) 2026 SUSE LLC
--
-- This software is licensed to you under the GNU General Public License,
-- version 2 (GPLv2). There is NO WARRANTY for this software, express or
-- implied, including the implied warranties of MERCHANTABILITY or FITNESS
-- FOR A PARTICULAR PURPOSE. You should have received a copy of GPLv2
-- along with this software; if not, see
-- http://www.gnu.org/licenses/old-licenses/gpl-2.0.txt.
--


CREATE TABLE suseClmDiffQueue
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_label     VARCHAR(24) NOT NULL
                       CONSTRAINT suse_clmdiffq_pl_fk
                           REFERENCES suseContentProject (label)
                           ON DELETE CASCADE,
    environment_label VARCHAR(16) NOT NULL,
    channel_label     VARCHAR(128) NOT NULL
                       CONSTRAINT suse_clmdiffq_cl_fk
                           REFERENCES rhnChannel (label)
                           ON DELETE CASCADE,
    next_action       TIMESTAMPTZ,
    created           TIMESTAMPTZ
                        DEFAULT (current_timestamp) NOT NULL,
    modified          TIMESTAMPTZ
                        DEFAULT (current_timestamp) NOT NULL
);

CREATE INDEX suse_clmdiffq_pec_idx
    ON suseClmDiffQueue (project_label, environment_label, channel_label);

CREATE INDEX suse_clmdiffq_na_pec_idx
    ON suseClmDiffQueue (next_action, project_label, environment_label, channel_label);
