# SPDX-FileCopyrightText: 2026 SUSE LLC
#
# SPDX-License-Identifier: GPL-2.0-only

# Makefile for the backend directory
#

# global defines which control this build and where we deploy files
PREFIX	=
export PREFIX

# what are we building...
SUBDIRS	= html modules

# macros and stuff
include Makefile.defs

