[[configuration-files-central]]
= Centrally Managed Configuration Files

Centrally-managed files are available to multiple systems.
Changing a file within a centrally-managed channel may result in changes to several systems.
Locally-managed files supersede centrally-managed files.
For more information about locally-managed files, see:
xref:reference:configuration/files-locally-managed.adoc[Locally Managed Configuration Files]

This page lists all files currently stored in your central configuration channel.
Click the [guimenu]``Path`` of a file to see its [guimenu]``Details`` tab.
Click the name of the [guimenu]``Configuration Channel`` to see the channel's [guimenu]``Overview`` tab.
Clicking [guimenu]``Systems Subscribed`` shows you all systems currently subscribed to the channel containing that file.
Click [guimenu]``Systems Overriding`` to see all systems that have a local (or override) version of the configuration file.
The centrally-managed file will not be deployed to those systems.
